-- One retry before the reconcile walks past a subscription that threw.
--
-- 0017_reconcile_cursor.sql advanced the cursor past the whole slice
-- whatever happened inside it. A subscription that failed -- a transient
-- Stripe error, a D1 blip -- was therefore not looked at again until the
-- walk lapped, which on a deployment sized for the Workers Free default is
-- one subscription a night and so a very long time to leave an entitlement
-- uncorrected or a missed payment unrecovered.
--
-- Holding the cursor at the failure instead would trade that for something
-- worse, and the codebase has already been bitten by it once: a row that
-- fails every night holds the front of the queue and starves every one
-- behind it. That is the exact failure `resumeStrandedPayouts` stamps each
-- attempt to avoid ("a row that fails every night moves to the back of the
-- queue instead of holding the front of it").
--
-- So this records *which* subscription the outstanding retry belongs to
-- rather than merely that one is outstanding. A boolean was the first cut
-- and it was wrong in a way worth writing down: during a retry run, a
-- different subscription failing for the first time found the flag already
-- set, so it was walked past with no retry of its own. Naming the id
-- separates "this one has had its second chance" from "this one has not
-- had its first", which is the whole distinction.
--
-- NULL means nothing is outstanding. A run holds for any failure that is
-- not the id named here, and walks past one that is.
ALTER TABLE billing_reconcile_cursor ADD COLUMN retry_of TEXT;
