import type { LookColors } from './looks.ts';

/**
 * The sites the home page's demonstration "builds".
 *
 * Every one of them is invented: the studios, the clinic and the fair do not
 * exist, and nothing here was generated by a model. They are the content of
 * a drawing, which is what the hero says it is. Real output is on /examples,
 * where each entry is exactly what vibld produced from the prompt beside it.
 *
 * The colours are each site's imaginary "direction A", measured with the
 * repository's contrast checker in `test/looks.test.ts` like every other
 * palette a miniature is drawn in.
 */

export type DemoSiteId =
  'pottery' | 'portfolio' | 'saas' | 'cafe' | 'clinic' | 'event' | 'app';

export interface DemoSite {
  id: DemoSiteId;
  /** The suggestion chip's label. */
  label: string;
  /** The project name the builder's title bar shows. */
  slug: string;
  prompt: string;
  /** The component name of the third section, for the code and the inspector. */
  section: string;
  text: {
    brand: string;
    links: readonly [string, string, string];
    nav: string;
    eyebrow: string;
    headline: string;
    lead: string;
    primary: string;
    secondary: string;
    cards: readonly [
      readonly [string, string],
      readonly [string, string],
      readonly [string, string],
    ];
  };
  /** How full each card's bar is, in percent. */
  bars: readonly [number, number, number];
  colors: LookColors;
}

/** The surfaces a demonstration site uses, from a handful of its colours. */
function siteColors(c: {
  page: string;
  ink: string;
  soft: string;
  card: string;
  primary: string;
  line: string;
  deco: readonly [string, string, string, string];
}): LookColors {
  return {
    page: { fill: c.page, ink: c.ink, soft: c.soft },
    card: { fill: c.card, ink: c.ink, soft: c.soft },
    panel: { fill: c.card, ink: c.ink, soft: c.soft },
    primary: { fill: c.primary, ink: '#FFFFFF' },
    accent: { fill: c.primary, ink: '#FFFFFF' },
    line: c.line,
    deco: c.deco,
  };
}

export const DEMO_SITES: Record<DemoSiteId, DemoSite> = {
  pottery: {
    id: 'pottery',
    label: 'Pottery class',
    slug: 'clay-saturdays',
    prompt:
      'A site for my Saturday wheel-throwing classes. People pick a two-hour slot and see a confirmation. Calm, let the pots speak.',
    section: 'SlotPicker',
    text: {
      brand: 'Clay Saturdays',
      links: ['Classes', 'Gallery', 'Studio'],
      nav: 'Book',
      eyebrow: 'Saturday wheel classes',
      headline: 'Throw your first pot this weekend.',
      lead: 'Two-hour slots at the wheel. Clay, glazes and firing included.',
      primary: 'Pick a slot',
      secondary: 'See the gallery',
      cards: [
        ['09:00', 'Beginners, two hours'],
        ['11:30', 'Open wheel'],
        ['14:00', 'Glazing session'],
      ],
    },
    bars: [70, 40, 85],
    colors: siteColors({
      page: '#E8EEEB',
      ink: '#16292A',
      soft: '#4D5F5F',
      card: '#F7FAF8',
      primary: '#1F6F6B',
      line: '#C9D6D2',
      deco: ['#CFE0DA', '#B5CFC7', '#1F6F6B', '#C9D9D3'],
    }),
  },
  portfolio: {
    id: 'portfolio',
    label: 'Portfolio',
    slug: 'mara-ceramics',
    prompt: 'A portfolio for my ceramics, big images, one page per series.',
    section: 'SeriesGrid',
    text: {
      brand: 'Mara Okafor',
      links: ['Work', 'About', 'Contact'],
      nav: 'Say hello',
      eyebrow: 'Ceramics and objects',
      headline: 'Quiet forms, made slowly.',
      lead: 'Selected series from the studio, one page for each body of work.',
      primary: 'View the work',
      secondary: 'About',
      cards: [
        ['Tidal', 'Stoneware series'],
        ['Ash', 'Wood-fired pieces'],
        ['Lumen', 'Porcelain lamps'],
      ],
    },
    bars: [90, 55, 35],
    colors: siteColors({
      page: '#F2F0EC',
      ink: '#1E232B',
      soft: '#555B66',
      card: '#FFFFFF',
      primary: '#2E3A48',
      line: '#D9D5CC',
      deco: ['#2E3A48', '#6E7F95', '#F2F0EC', '#E9C46A'],
    }),
  },
  saas: {
    id: 'saas',
    label: 'SaaS landing',
    slug: 'ledgerly',
    prompt:
      'A landing page for an invoicing tool, with a pricing table and a sign-up form.',
    section: 'Features',
    text: {
      brand: 'Ledgerly',
      links: ['Product', 'Pricing', 'Docs'],
      nav: 'Start',
      eyebrow: 'Invoicing for small studios',
      headline: 'Send the invoice. Get paid. Move on.',
      lead: 'Recurring invoices, polite reminders and a clean client portal.',
      primary: 'Start free',
      secondary: 'See pricing',
      cards: [
        ['Invoices', 'Recurring or one-off'],
        ['Reminders', 'Polite, automatic'],
        ['Portal', 'Clients pay in one click'],
      ],
    },
    bars: [80, 60, 70],
    colors: siteColors({
      page: '#F7F5EF',
      ink: '#14213D',
      soft: '#4A5468',
      card: '#FFFFFF',
      primary: '#14213D',
      line: '#DEDBD2',
      deco: ['#FFE7BD', '#FFC878', '#C96A00', '#FFFFFF'],
    }),
  },
  cafe: {
    id: 'cafe',
    label: 'Cafe',
    slug: 'morrow-cafe',
    prompt: 'A cafe site with the menu, opening hours and a map link.',
    section: 'MenuList',
    text: {
      brand: 'Morrow Cafe',
      links: ['Menu', 'Hours', 'Visit'],
      nav: 'Find us',
      eyebrow: 'Open from seven',
      headline: 'Good coffee, slow mornings.',
      lead: 'A seasonal menu, bread baked in house and a window seat if you are early.',
      primary: 'See the menu',
      secondary: 'Opening hours',
      cards: [
        ['Espresso', 'Single origin'],
        ['Pastries', 'Baked this morning'],
        ['Lunch', 'From eleven'],
      ],
    },
    bars: [60, 85, 45],
    colors: siteColors({
      page: '#F5EDE3',
      ink: '#2B1B12',
      soft: '#6A5140',
      card: '#FFF9F2',
      primary: '#6F3B1F',
      line: '#E3D3C2',
      deco: ['#E9D3BC', '#D2AE8B', '#6F3B1F', '#FFF9F2'],
    }),
  },
  clinic: {
    id: 'clinic',
    label: 'Clinic',
    slug: 'harbour-physio',
    prompt:
      'A physiotherapy clinic site where patients request an appointment slot.',
    section: 'Services',
    text: {
      brand: 'Harbor Physio',
      links: ['Treatments', 'Team', 'Visit'],
      nav: 'Book',
      eyebrow: 'Physiotherapy clinic',
      headline: 'Move without the ache.',
      lead: 'Assessment, treatment and a plan you can follow at home.',
      primary: 'Request a slot',
      secondary: 'Treatments',
      cards: [
        ['Assessment', 'First visit'],
        ['Sports injury', 'Rehab plans'],
        ['Back and neck', 'Hands-on care'],
      ],
    },
    bars: [50, 75, 65],
    colors: siteColors({
      page: '#EEF6F6',
      ink: '#0F2A2E',
      soft: '#48656A',
      card: '#FFFFFF',
      primary: '#0B6E77',
      line: '#CFE3E4',
      deco: ['#D4EEEF', '#B3DDE0', '#0B6E77', '#FFFFFF'],
    }),
  },
  event: {
    id: 'event',
    label: 'Event',
    slug: 'kiln-fair',
    prompt:
      'A page for our community pottery fair, with a schedule and a signup.',
    section: 'Schedule',
    text: {
      brand: 'Kiln Fair',
      links: ['Schedule', 'Makers', 'Tickets'],
      nav: 'Tickets',
      eyebrow: 'Community pottery fair',
      headline: 'A weekend of mud and makers.',
      lead: 'Demos, a raku firing and stalls from local studios.',
      primary: 'Get tickets',
      secondary: 'Schedule',
      cards: [
        ['Saturday', 'Stalls and demos'],
        ['Sunday', 'Raku firing'],
        ['Evening', 'Kiln opening'],
      ],
    },
    bars: [85, 65, 40],
    colors: siteColors({
      page: '#FFF0F4',
      ink: '#2A0F1C',
      soft: '#6B3D52',
      card: '#FFFFFF',
      primary: '#C2255C',
      line: '#F4CFDB',
      deco: ['#FFD1DE', '#FFB0C6', '#C2255C', '#FFFFFF'],
    }),
  },
  app: {
    id: 'app',
    label: 'Habit app',
    slug: 'streak',
    prompt:
      'A habit tracker: add a habit, tick it off each day, see the streak.',
    section: 'HabitList',
    text: {
      brand: 'Streak',
      links: ['Today', 'Habits', 'Stats'],
      nav: 'New habit',
      eyebrow: 'Habit tracker',
      headline: 'Small habits, every day.',
      lead: 'Add a habit, tick it off, and watch the streak grow.',
      primary: 'Add a habit',
      secondary: 'See stats',
      cards: [
        ['Read', 'Twenty minutes'],
        ['Walk', 'After lunch'],
        ['Stretch', 'Before bed'],
      ],
    },
    bars: [60, 80, 30],
    colors: siteColors({
      page: '#F1F5EE',
      ink: '#1C2A1E',
      soft: '#4B5E4E',
      card: '#FFFFFF',
      primary: '#2F7A45',
      line: '#D3E0D0',
      deco: ['#DDEFD8', '#C2E0BA', '#2F7A45', '#FFFFFF'],
    }),
  },
};

export const DEMO_SITE_IDS = Object.keys(DEMO_SITES) as DemoSiteId[];

/**
 * Which demonstration a typed request most resembles.
 *
 * Keyword matching and nothing more, which is exactly as clever as a page
 * that does not call a model can honestly be. Anything unmatched builds the
 * pottery studio.
 */
const KEYWORDS: readonly (readonly [DemoSiteId, RegExp])[] = [
  ['portfolio', /portfolio|photograph|artist|illustrat|designer/i],
  ['cafe', /caf[eé]|coffee|bakery|restaurant|\bbar\b|menu/i],
  ['clinic', /clinic|dental|dentist|physio|doctor|therap|health/i],
  ['event', /event|fair|festival|conference|wedding|meetup|concert/i],
  ['app', /habit|tracker|todo|to-do|\bapp\b/i],
  ['saas', /saas|startup|invoice|product|tool|software|landing/i],
  ['pottery', /pottery|ceramic|class|course|workshop|lesson/i],
];

export function siteForRequest(request: string): DemoSiteId {
  for (const [id, pattern] of KEYWORDS) {
    if (pattern.test(request)) return id;
  }
  return 'pottery';
}
