// Generated by scripts/template-fonts.ts. Do not edit: run it again.
import type { TemplateFont } from '../scripts/template-fonts.ts';

export const TEMPLATE_FONTS: Record<string, TemplateFont> = {
  "AR One Sans": {
    "slug": "ar-one-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/ar-one-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/ar-one-sans/ar-one-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/ar-one-sans/LICENSE.txt"
  },
  "Afacad": {
    "slug": "afacad",
    "category": "sans-serif",
    "source": "@fontsource-variable/afacad 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/afacad/afacad-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/afacad/LICENSE.txt"
  },
  "Afacad Flux": {
    "slug": "afacad-flux",
    "category": "sans-serif",
    "source": "@fontsource-variable/afacad-flux 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/afacad-flux/afacad-flux-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/afacad-flux/LICENSE.txt"
  },
  "Alan Sans": {
    "slug": "alan-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/alan-sans 5.3.1",
    "files": [
      {
        "file": "/fonts/templates/alan-sans/alan-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/alan-sans/LICENSE.txt"
  },
  "Albert Sans": {
    "slug": "albert-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/albert-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/albert-sans/albert-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/albert-sans/LICENSE.txt"
  },
  "Alegreya": {
    "slug": "alegreya",
    "category": "serif",
    "source": "@fontsource-variable/alegreya 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/alegreya/alegreya-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/alegreya/LICENSE.txt"
  },
  "Alegreya Sans": {
    "slug": "alegreya-sans",
    "category": "sans-serif",
    "source": "@fontsource/alegreya-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/alegreya-sans/alegreya-sans-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/alegreya-sans/alegreya-sans-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/alegreya-sans/LICENSE.txt"
  },
  "Ancizar Sans": {
    "slug": "ancizar-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/ancizar-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/ancizar-sans/ancizar-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/ancizar-sans/LICENSE.txt"
  },
  "Anek Latin": {
    "slug": "anek-latin",
    "category": "sans-serif",
    "source": "@fontsource-variable/anek-latin 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/anek-latin/anek-latin-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/anek-latin/LICENSE.txt"
  },
  "Anonymous Pro": {
    "slug": "anonymous-pro",
    "category": "monospace",
    "source": "@fontsource/anonymous-pro 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/anonymous-pro/anonymous-pro-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/anonymous-pro/anonymous-pro-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/anonymous-pro/LICENSE.txt"
  },
  "Anton": {
    "slug": "anton",
    "category": "sans-serif",
    "source": "@fontsource/anton 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/anton/anton-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/anton/LICENSE.txt"
  },
  "Antonio": {
    "slug": "antonio",
    "category": "sans-serif",
    "source": "@fontsource-variable/antonio 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/antonio/antonio-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/antonio/LICENSE.txt"
  },
  "Archivo": {
    "slug": "archivo",
    "category": "sans-serif",
    "source": "@fontsource-variable/archivo 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/archivo/archivo-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/archivo/LICENSE.txt"
  },
  "Archivo Black": {
    "slug": "archivo-black",
    "category": "sans-serif",
    "source": "@fontsource/archivo-black 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/archivo-black/archivo-black-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/archivo-black/LICENSE.txt"
  },
  "Arimo": {
    "slug": "arimo",
    "category": "sans-serif",
    "source": "@fontsource-variable/arimo 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/arimo/arimo-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/arimo/LICENSE.txt"
  },
  "Asap": {
    "slug": "asap",
    "category": "sans-serif",
    "source": "@fontsource-variable/asap 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/asap/asap-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/asap/LICENSE.txt"
  },
  "Assistant": {
    "slug": "assistant",
    "category": "sans-serif",
    "source": "@fontsource-variable/assistant 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/assistant/assistant-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/assistant/LICENSE.txt"
  },
  "Atkinson Hyperlegible": {
    "slug": "atkinson-hyperlegible",
    "category": "sans-serif",
    "source": "@fontsource/atkinson-hyperlegible 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/atkinson-hyperlegible/atkinson-hyperlegible-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/atkinson-hyperlegible/atkinson-hyperlegible-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/atkinson-hyperlegible/LICENSE.txt"
  },
  "Atkinson Hyperlegible Next": {
    "slug": "atkinson-hyperlegible-next",
    "category": "sans-serif",
    "source": "@fontsource-variable/atkinson-hyperlegible-next 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/atkinson-hyperlegible-next/atkinson-hyperlegible-next-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/atkinson-hyperlegible-next/LICENSE.txt"
  },
  "Azeret Mono": {
    "slug": "azeret-mono",
    "category": "monospace",
    "source": "@fontsource-variable/azeret-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/azeret-mono/azeret-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/azeret-mono/LICENSE.txt"
  },
  "B612 Mono": {
    "slug": "b612-mono",
    "category": "monospace",
    "source": "@fontsource/b612-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/b612-mono/b612-mono-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/b612-mono/b612-mono-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/b612-mono/LICENSE.txt"
  },
  "Bagel Fat One": {
    "slug": "bagel-fat-one",
    "category": "display",
    "source": "@fontsource/bagel-fat-one 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/bagel-fat-one/bagel-fat-one-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/bagel-fat-one/LICENSE.txt"
  },
  "Bai Jamjuree": {
    "slug": "bai-jamjuree",
    "category": "sans-serif",
    "source": "@fontsource/bai-jamjuree 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/bai-jamjuree/bai-jamjuree-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/bai-jamjuree/bai-jamjuree-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/bai-jamjuree/LICENSE.txt"
  },
  "Baloo 2": {
    "slug": "baloo-2",
    "category": "display",
    "source": "@fontsource-variable/baloo-2 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/baloo-2/baloo-2-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/baloo-2/LICENSE.txt"
  },
  "Baloo Da 2": {
    "slug": "baloo-da-2",
    "category": "display",
    "source": "@fontsource-variable/baloo-da-2 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/baloo-da-2/baloo-da-2-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/baloo-da-2/LICENSE.txt"
  },
  "Barlow": {
    "slug": "barlow",
    "category": "sans-serif",
    "source": "@fontsource/barlow 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/barlow/barlow-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/barlow/barlow-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/barlow/LICENSE.txt"
  },
  "Barlow Condensed": {
    "slug": "barlow-condensed",
    "category": "sans-serif",
    "source": "@fontsource/barlow-condensed 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/barlow-condensed/barlow-condensed-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/barlow-condensed/barlow-condensed-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/barlow-condensed/LICENSE.txt"
  },
  "Barlow Semi Condensed": {
    "slug": "barlow-semi-condensed",
    "category": "sans-serif",
    "source": "@fontsource/barlow-semi-condensed 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/barlow-semi-condensed/barlow-semi-condensed-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/barlow-semi-condensed/barlow-semi-condensed-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/barlow-semi-condensed/LICENSE.txt"
  },
  "Baskervville": {
    "slug": "baskervville",
    "category": "serif",
    "source": "@fontsource-variable/baskervville 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/baskervville/baskervville-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/baskervville/LICENSE.txt"
  },
  "Be Vietnam Pro": {
    "slug": "be-vietnam-pro",
    "category": "sans-serif",
    "source": "@fontsource/be-vietnam-pro 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/be-vietnam-pro/be-vietnam-pro-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/be-vietnam-pro/be-vietnam-pro-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/be-vietnam-pro/LICENSE.txt"
  },
  "Bebas Neue": {
    "slug": "bebas-neue",
    "category": "sans-serif",
    "source": "@fontsource/bebas-neue 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/bebas-neue/bebas-neue-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/bebas-neue/LICENSE.txt"
  },
  "Belanosima": {
    "slug": "belanosima",
    "category": "sans-serif",
    "source": "@fontsource/belanosima 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/belanosima/belanosima-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/belanosima/belanosima-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/belanosima/LICENSE.txt"
  },
  "Bodoni Moda": {
    "slug": "bodoni-moda",
    "category": "serif",
    "source": "@fontsource-variable/bodoni-moda 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/bodoni-moda/bodoni-moda-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/bodoni-moda/LICENSE.txt"
  },
  "Bricolage Grotesque": {
    "slug": "bricolage-grotesque",
    "category": "sans-serif",
    "source": "@fontsource-variable/bricolage-grotesque 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/bricolage-grotesque/bricolage-grotesque-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/bricolage-grotesque/LICENSE.txt"
  },
  "Brygada 1918": {
    "slug": "brygada-1918",
    "category": "serif",
    "source": "@fontsource-variable/brygada-1918 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/brygada-1918/brygada-1918-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/brygada-1918/LICENSE.txt"
  },
  "Cabin": {
    "slug": "cabin",
    "category": "sans-serif",
    "source": "@fontsource-variable/cabin 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/cabin/cabin-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/cabin/LICENSE.txt"
  },
  "Castoro": {
    "slug": "castoro",
    "category": "serif",
    "source": "@fontsource/castoro 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/castoro/castoro-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/castoro/LICENSE.txt"
  },
  "Catamaran": {
    "slug": "catamaran",
    "category": "sans-serif",
    "source": "@fontsource-variable/catamaran 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/catamaran/catamaran-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/catamaran/LICENSE.txt"
  },
  "Caveat": {
    "slug": "caveat",
    "category": "handwriting",
    "source": "@fontsource-variable/caveat 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/caveat/caveat-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/caveat/LICENSE.txt"
  },
  "Caveat Brush": {
    "slug": "caveat-brush",
    "category": "handwriting",
    "source": "@fontsource/caveat-brush 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/caveat-brush/caveat-brush-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/caveat-brush/LICENSE.txt"
  },
  "Chakra Petch": {
    "slug": "chakra-petch",
    "category": "sans-serif",
    "source": "@fontsource/chakra-petch 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/chakra-petch/chakra-petch-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/chakra-petch/chakra-petch-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/chakra-petch/LICENSE.txt"
  },
  "Chivo": {
    "slug": "chivo",
    "category": "sans-serif",
    "source": "@fontsource-variable/chivo 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/chivo/chivo-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/chivo/LICENSE.txt"
  },
  "Chivo Mono": {
    "slug": "chivo-mono",
    "category": "monospace",
    "source": "@fontsource-variable/chivo-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/chivo-mono/chivo-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/chivo-mono/LICENSE.txt"
  },
  "Comme": {
    "slug": "comme",
    "category": "sans-serif",
    "source": "@fontsource-variable/comme 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/comme/comme-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/comme/LICENSE.txt"
  },
  "Commissioner": {
    "slug": "commissioner",
    "category": "sans-serif",
    "source": "@fontsource-variable/commissioner 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/commissioner/commissioner-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/commissioner/LICENSE.txt"
  },
  "Cormorant": {
    "slug": "cormorant",
    "category": "serif",
    "source": "@fontsource-variable/cormorant 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/cormorant/cormorant-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/cormorant/LICENSE.txt"
  },
  "Cormorant Garamond": {
    "slug": "cormorant-garamond",
    "category": "serif",
    "source": "@fontsource-variable/cormorant-garamond 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/cormorant-garamond/cormorant-garamond-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/cormorant-garamond/LICENSE.txt"
  },
  "Courier Prime": {
    "slug": "courier-prime",
    "category": "monospace",
    "source": "@fontsource/courier-prime 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/courier-prime/courier-prime-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/courier-prime/courier-prime-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/courier-prime/LICENSE.txt"
  },
  "Cousine": {
    "slug": "cousine",
    "category": "monospace",
    "source": "@fontsource/cousine 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/cousine/cousine-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/cousine/cousine-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/cousine/LICENSE.txt"
  },
  "Crimson Pro": {
    "slug": "crimson-pro",
    "category": "serif",
    "source": "@fontsource-variable/crimson-pro 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/crimson-pro/crimson-pro-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/crimson-pro/LICENSE.txt"
  },
  "Cutive Mono": {
    "slug": "cutive-mono",
    "category": "monospace",
    "source": "@fontsource/cutive-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/cutive-mono/cutive-mono-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/cutive-mono/LICENSE.txt"
  },
  "DM Mono": {
    "slug": "dm-mono",
    "category": "monospace",
    "source": "@fontsource/dm-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/dm-mono/dm-mono-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/dm-mono/dm-mono-latin-500-normal.woff2",
        "weight": "500"
      }
    ],
    "licence": "/fonts/templates/dm-mono/LICENSE.txt"
  },
  "DM Sans": {
    "slug": "dm-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/dm-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/dm-sans/dm-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/dm-sans/LICENSE.txt"
  },
  "DM Serif Display": {
    "slug": "dm-serif-display",
    "category": "serif",
    "source": "@fontsource/dm-serif-display 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/dm-serif-display/dm-serif-display-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/dm-serif-display/LICENSE.txt"
  },
  "Dancing Script": {
    "slug": "dancing-script",
    "category": "handwriting",
    "source": "@fontsource-variable/dancing-script 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/dancing-script/dancing-script-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/dancing-script/LICENSE.txt"
  },
  "Dela Gothic One": {
    "slug": "dela-gothic-one",
    "category": "display",
    "source": "@fontsource/dela-gothic-one 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/dela-gothic-one/dela-gothic-one-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/dela-gothic-one/LICENSE.txt"
  },
  "EB Garamond": {
    "slug": "eb-garamond",
    "category": "serif",
    "source": "@fontsource-variable/eb-garamond 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/eb-garamond/eb-garamond-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/eb-garamond/LICENSE.txt"
  },
  "Encode Sans": {
    "slug": "encode-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/encode-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/encode-sans/encode-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/encode-sans/LICENSE.txt"
  },
  "Encode Sans Expanded": {
    "slug": "encode-sans-expanded",
    "category": "sans-serif",
    "source": "@fontsource/encode-sans-expanded 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/encode-sans-expanded/encode-sans-expanded-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/encode-sans-expanded/encode-sans-expanded-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/encode-sans-expanded/LICENSE.txt"
  },
  "Epilogue": {
    "slug": "epilogue",
    "category": "sans-serif",
    "source": "@fontsource-variable/epilogue 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/epilogue/epilogue-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/epilogue/LICENSE.txt"
  },
  "Exo 2": {
    "slug": "exo-2",
    "category": "sans-serif",
    "source": "@fontsource-variable/exo-2 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/exo-2/exo-2-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/exo-2/LICENSE.txt"
  },
  "Familjen Grotesk": {
    "slug": "familjen-grotesk",
    "category": "sans-serif",
    "source": "@fontsource-variable/familjen-grotesk 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/familjen-grotesk/familjen-grotesk-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/familjen-grotesk/LICENSE.txt"
  },
  "Faustina": {
    "slug": "faustina",
    "category": "serif",
    "source": "@fontsource-variable/faustina 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/faustina/faustina-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/faustina/LICENSE.txt"
  },
  "Figtree": {
    "slug": "figtree",
    "category": "sans-serif",
    "source": "@fontsource-variable/figtree 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/figtree/figtree-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/figtree/LICENSE.txt"
  },
  "Fira Code": {
    "slug": "fira-code",
    "category": "monospace",
    "source": "@fontsource-variable/fira-code 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/fira-code/fira-code-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/fira-code/LICENSE.txt"
  },
  "Fira Mono": {
    "slug": "fira-mono",
    "category": "monospace",
    "source": "@fontsource/fira-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/fira-mono/fira-mono-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/fira-mono/fira-mono-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/fira-mono/LICENSE.txt"
  },
  "Fira Sans": {
    "slug": "fira-sans",
    "category": "sans-serif",
    "source": "@fontsource/fira-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/fira-sans/fira-sans-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/fira-sans/fira-sans-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/fira-sans/LICENSE.txt"
  },
  "Fira Sans Condensed": {
    "slug": "fira-sans-condensed",
    "category": "sans-serif",
    "source": "@fontsource/fira-sans-condensed 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/fira-sans-condensed/fira-sans-condensed-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/fira-sans-condensed/fira-sans-condensed-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/fira-sans-condensed/LICENSE.txt"
  },
  "Fragment Mono": {
    "slug": "fragment-mono",
    "category": "monospace",
    "source": "@fontsource/fragment-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/fragment-mono/fragment-mono-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/fragment-mono/LICENSE.txt"
  },
  "Frank Ruhl Libre": {
    "slug": "frank-ruhl-libre",
    "category": "serif",
    "source": "@fontsource-variable/frank-ruhl-libre 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/frank-ruhl-libre/frank-ruhl-libre-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/frank-ruhl-libre/LICENSE.txt"
  },
  "Fraunces": {
    "slug": "fraunces",
    "category": "serif",
    "source": "@fontsource-variable/fraunces 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/fraunces/fraunces-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/fraunces/LICENSE.txt"
  },
  "Fredoka": {
    "slug": "fredoka",
    "category": "sans-serif",
    "source": "@fontsource-variable/fredoka 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/fredoka/fredoka-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/fredoka/LICENSE.txt"
  },
  "Funnel Sans": {
    "slug": "funnel-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/funnel-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/funnel-sans/funnel-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/funnel-sans/LICENSE.txt"
  },
  "Gabarito": {
    "slug": "gabarito",
    "category": "display",
    "source": "@fontsource-variable/gabarito 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/gabarito/gabarito-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/gabarito/LICENSE.txt"
  },
  "Gantari": {
    "slug": "gantari",
    "category": "sans-serif",
    "source": "@fontsource-variable/gantari 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/gantari/gantari-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/gantari/LICENSE.txt"
  },
  "Geist": {
    "slug": "geist",
    "category": "sans-serif",
    "source": "@fontsource-variable/geist 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/geist/geist-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/geist/LICENSE.txt"
  },
  "Geist Mono": {
    "slug": "geist-mono",
    "category": "monospace",
    "source": "@fontsource-variable/geist-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/geist-mono/geist-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/geist-mono/LICENSE.txt"
  },
  "Gelasio": {
    "slug": "gelasio",
    "category": "serif",
    "source": "@fontsource-variable/gelasio 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/gelasio/gelasio-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/gelasio/LICENSE.txt"
  },
  "Geologica": {
    "slug": "geologica",
    "category": "sans-serif",
    "source": "@fontsource-variable/geologica 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/geologica/geologica-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/geologica/LICENSE.txt"
  },
  "Georama": {
    "slug": "georama",
    "category": "sans-serif",
    "source": "@fontsource-variable/georama 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/georama/georama-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/georama/LICENSE.txt"
  },
  "Gilda Display": {
    "slug": "gilda-display",
    "category": "serif",
    "source": "@fontsource/gilda-display 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/gilda-display/gilda-display-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/gilda-display/LICENSE.txt"
  },
  "Gloock": {
    "slug": "gloock",
    "category": "serif",
    "source": "@fontsource/gloock 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/gloock/gloock-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/gloock/LICENSE.txt"
  },
  "Glory": {
    "slug": "glory",
    "category": "sans-serif",
    "source": "@fontsource-variable/glory 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/glory/glory-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/glory/LICENSE.txt"
  },
  "Golos Text": {
    "slug": "golos-text",
    "category": "sans-serif",
    "source": "@fontsource-variable/golos-text 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/golos-text/golos-text-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/golos-text/LICENSE.txt"
  },
  "Google Sans": {
    "slug": "google-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/google-sans 5.3.1",
    "files": [
      {
        "file": "/fonts/templates/google-sans/google-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/google-sans/LICENSE.txt"
  },
  "Google Sans Code": {
    "slug": "google-sans-code",
    "category": "monospace",
    "source": "@fontsource-variable/google-sans-code 5.3.1",
    "files": [
      {
        "file": "/fonts/templates/google-sans-code/google-sans-code-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/google-sans-code/LICENSE.txt"
  },
  "Google Sans Flex": {
    "slug": "google-sans-flex",
    "category": "sans-serif",
    "source": "@fontsource-variable/google-sans-flex 5.3.1",
    "files": [
      {
        "file": "/fonts/templates/google-sans-flex/google-sans-flex-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/google-sans-flex/LICENSE.txt"
  },
  "Gothic A1": {
    "slug": "gothic-a1",
    "category": "sans-serif",
    "source": "@fontsource/gothic-a1 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/gothic-a1/gothic-a1-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/gothic-a1/gothic-a1-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/gothic-a1/LICENSE.txt"
  },
  "Great Vibes": {
    "slug": "great-vibes",
    "category": "handwriting",
    "source": "@fontsource/great-vibes 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/great-vibes/great-vibes-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/great-vibes/LICENSE.txt"
  },
  "Hanken Grotesk": {
    "slug": "hanken-grotesk",
    "category": "sans-serif",
    "source": "@fontsource-variable/hanken-grotesk 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/hanken-grotesk/hanken-grotesk-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/hanken-grotesk/LICENSE.txt"
  },
  "Hedvig Letters Serif": {
    "slug": "hedvig-letters-serif",
    "category": "serif",
    "source": "@fontsource/hedvig-letters-serif 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/hedvig-letters-serif/hedvig-letters-serif-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/hedvig-letters-serif/LICENSE.txt"
  },
  "Heebo": {
    "slug": "heebo",
    "category": "sans-serif",
    "source": "@fontsource-variable/heebo 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/heebo/heebo-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/heebo/LICENSE.txt"
  },
  "Hind": {
    "slug": "hind",
    "category": "sans-serif",
    "source": "@fontsource/hind 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/hind/hind-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/hind/hind-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/hind/LICENSE.txt"
  },
  "Homemade Apple": {
    "slug": "homemade-apple",
    "category": "handwriting",
    "source": "@fontsource/homemade-apple 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/homemade-apple/homemade-apple-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/homemade-apple/LICENSE.txt"
  },
  "Host Grotesk": {
    "slug": "host-grotesk",
    "category": "sans-serif",
    "source": "@fontsource-variable/host-grotesk 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/host-grotesk/host-grotesk-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/host-grotesk/LICENSE.txt"
  },
  "Hubot Sans": {
    "slug": "hubot-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/hubot-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/hubot-sans/hubot-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/hubot-sans/LICENSE.txt"
  },
  "IBM Plex Mono": {
    "slug": "ibm-plex-mono",
    "category": "monospace",
    "source": "@fontsource/ibm-plex-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/ibm-plex-mono/ibm-plex-mono-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/ibm-plex-mono/ibm-plex-mono-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/ibm-plex-mono/LICENSE.txt"
  },
  "IBM Plex Sans": {
    "slug": "ibm-plex-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/ibm-plex-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/ibm-plex-sans/ibm-plex-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/ibm-plex-sans/LICENSE.txt"
  },
  "Imbue": {
    "slug": "imbue",
    "category": "serif",
    "source": "@fontsource-variable/imbue 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/imbue/imbue-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/imbue/LICENSE.txt"
  },
  "Inclusive Sans": {
    "slug": "inclusive-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/inclusive-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/inclusive-sans/inclusive-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/inclusive-sans/LICENSE.txt"
  },
  "Inconsolata": {
    "slug": "inconsolata",
    "category": "monospace",
    "source": "@fontsource-variable/inconsolata 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/inconsolata/inconsolata-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/inconsolata/LICENSE.txt"
  },
  "Instrument Sans": {
    "slug": "instrument-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/instrument-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/instrument-sans/instrument-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/instrument-sans/LICENSE.txt"
  },
  "Instrument Serif": {
    "slug": "instrument-serif",
    "category": "serif",
    "source": "@fontsource/instrument-serif 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/instrument-serif/instrument-serif-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/instrument-serif/LICENSE.txt"
  },
  "Intel One Mono": {
    "slug": "intel-one-mono",
    "category": "monospace",
    "source": "@fontsource-variable/intel-one-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/intel-one-mono/intel-one-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/intel-one-mono/LICENSE.txt"
  },
  "Inter": {
    "slug": "inter",
    "category": "sans-serif",
    "source": "@fontsource-variable/inter 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/inter/inter-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/inter/LICENSE.txt"
  },
  "Inter Tight": {
    "slug": "inter-tight",
    "category": "sans-serif",
    "source": "@fontsource-variable/inter-tight 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/inter-tight/inter-tight-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/inter-tight/LICENSE.txt"
  },
  "JetBrains Mono": {
    "slug": "jetbrains-mono",
    "category": "monospace",
    "source": "@fontsource-variable/jetbrains-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/jetbrains-mono/jetbrains-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/jetbrains-mono/LICENSE.txt"
  },
  "Josefin Sans": {
    "slug": "josefin-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/josefin-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/josefin-sans/josefin-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/josefin-sans/LICENSE.txt"
  },
  "Jost": {
    "slug": "jost",
    "category": "sans-serif",
    "source": "@fontsource-variable/jost 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/jost/jost-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/jost/LICENSE.txt"
  },
  "Kalam": {
    "slug": "kalam",
    "category": "handwriting",
    "source": "@fontsource/kalam 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/kalam/kalam-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/kalam/kalam-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/kalam/LICENSE.txt"
  },
  "Kanit": {
    "slug": "kanit",
    "category": "sans-serif",
    "source": "@fontsource/kanit 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/kanit/kanit-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/kanit/kanit-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/kanit/LICENSE.txt"
  },
  "Karla": {
    "slug": "karla",
    "category": "sans-serif",
    "source": "@fontsource-variable/karla 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/karla/karla-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/karla/LICENSE.txt"
  },
  "Kumbh Sans": {
    "slug": "kumbh-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/kumbh-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/kumbh-sans/kumbh-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/kumbh-sans/LICENSE.txt"
  },
  "La Belle Aurore": {
    "slug": "la-belle-aurore",
    "category": "handwriting",
    "source": "@fontsource/la-belle-aurore 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/la-belle-aurore/la-belle-aurore-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/la-belle-aurore/LICENSE.txt"
  },
  "Lato": {
    "slug": "lato",
    "category": "sans-serif",
    "source": "@fontsource/lato 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/lato/lato-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/lato/lato-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/lato/LICENSE.txt"
  },
  "League Gothic": {
    "slug": "league-gothic",
    "category": "sans-serif",
    "source": "@fontsource/league-gothic 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/league-gothic/league-gothic-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/league-gothic/LICENSE.txt"
  },
  "League Spartan": {
    "slug": "league-spartan",
    "category": "sans-serif",
    "source": "@fontsource-variable/league-spartan 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/league-spartan/league-spartan-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/league-spartan/LICENSE.txt"
  },
  "Lexend": {
    "slug": "lexend",
    "category": "sans-serif",
    "source": "@fontsource-variable/lexend 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/lexend/lexend-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/lexend/LICENSE.txt"
  },
  "Lexend Deca": {
    "slug": "lexend-deca",
    "category": "sans-serif",
    "source": "@fontsource-variable/lexend-deca 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/lexend-deca/lexend-deca-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/lexend-deca/LICENSE.txt"
  },
  "Lexend Exa": {
    "slug": "lexend-exa",
    "category": "sans-serif",
    "source": "@fontsource-variable/lexend-exa 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/lexend-exa/lexend-exa-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/lexend-exa/LICENSE.txt"
  },
  "Lexend Zetta": {
    "slug": "lexend-zetta",
    "category": "sans-serif",
    "source": "@fontsource-variable/lexend-zetta 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/lexend-zetta/lexend-zetta-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/lexend-zetta/LICENSE.txt"
  },
  "Libre Baskerville": {
    "slug": "libre-baskerville",
    "category": "serif",
    "source": "@fontsource-variable/libre-baskerville 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/libre-baskerville/libre-baskerville-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/libre-baskerville/LICENSE.txt"
  },
  "Libre Bodoni": {
    "slug": "libre-bodoni",
    "category": "serif",
    "source": "@fontsource-variable/libre-bodoni 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/libre-bodoni/libre-bodoni-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/libre-bodoni/LICENSE.txt"
  },
  "Libre Caslon Condensed": {
    "slug": "libre-caslon-condensed",
    "category": "serif",
    "source": "@fontsource/libre-caslon-condensed 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/libre-caslon-condensed/libre-caslon-condensed-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/libre-caslon-condensed/libre-caslon-condensed-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/libre-caslon-condensed/LICENSE.txt"
  },
  "Libre Caslon Display": {
    "slug": "libre-caslon-display",
    "category": "serif",
    "source": "@fontsource/libre-caslon-display 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/libre-caslon-display/libre-caslon-display-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/libre-caslon-display/LICENSE.txt"
  },
  "Libre Caslon Text": {
    "slug": "libre-caslon-text",
    "category": "serif",
    "source": "@fontsource/libre-caslon-text 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/libre-caslon-text/libre-caslon-text-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/libre-caslon-text/libre-caslon-text-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/libre-caslon-text/LICENSE.txt"
  },
  "Libre Franklin": {
    "slug": "libre-franklin",
    "category": "sans-serif",
    "source": "@fontsource-variable/libre-franklin 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/libre-franklin/libre-franklin-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/libre-franklin/LICENSE.txt"
  },
  "Literata": {
    "slug": "literata",
    "category": "serif",
    "source": "@fontsource-variable/literata 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/literata/literata-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/literata/LICENSE.txt"
  },
  "Livvic": {
    "slug": "livvic",
    "category": "sans-serif",
    "source": "@fontsource/livvic 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/livvic/livvic-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/livvic/livvic-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/livvic/LICENSE.txt"
  },
  "Lora": {
    "slug": "lora",
    "category": "serif",
    "source": "@fontsource-variable/lora 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/lora/lora-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/lora/LICENSE.txt"
  },
  "M PLUS 2": {
    "slug": "m-plus-2",
    "category": "sans-serif",
    "source": "@fontsource-variable/m-plus-2 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/m-plus-2/m-plus-2-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/m-plus-2/LICENSE.txt"
  },
  "M PLUS Rounded 1c": {
    "slug": "m-plus-rounded-1c",
    "category": "sans-serif",
    "source": "@fontsource/m-plus-rounded-1c 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/m-plus-rounded-1c/m-plus-rounded-1c-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/m-plus-rounded-1c/m-plus-rounded-1c-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/m-plus-rounded-1c/LICENSE.txt"
  },
  "Manrope": {
    "slug": "manrope",
    "category": "sans-serif",
    "source": "@fontsource-variable/manrope 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/manrope/manrope-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/manrope/LICENSE.txt"
  },
  "Martian Mono": {
    "slug": "martian-mono",
    "category": "monospace",
    "source": "@fontsource-variable/martian-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/martian-mono/martian-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/martian-mono/LICENSE.txt"
  },
  "Maven Pro": {
    "slug": "maven-pro",
    "category": "sans-serif",
    "source": "@fontsource-variable/maven-pro 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/maven-pro/maven-pro-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/maven-pro/LICENSE.txt"
  },
  "Merriweather": {
    "slug": "merriweather",
    "category": "serif",
    "source": "@fontsource-variable/merriweather 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/merriweather/merriweather-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/merriweather/LICENSE.txt"
  },
  "Merriweather Sans": {
    "slug": "merriweather-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/merriweather-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/merriweather-sans/merriweather-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/merriweather-sans/LICENSE.txt"
  },
  "Miranda Sans": {
    "slug": "miranda-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/miranda-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/miranda-sans/miranda-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/miranda-sans/LICENSE.txt"
  },
  "Mona Sans": {
    "slug": "mona-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/mona-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/mona-sans/mona-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/mona-sans/LICENSE.txt"
  },
  "Montserrat": {
    "slug": "montserrat",
    "category": "sans-serif",
    "source": "@fontsource-variable/montserrat 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/montserrat/montserrat-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/montserrat/LICENSE.txt"
  },
  "Montserrat Alternates": {
    "slug": "montserrat-alternates",
    "category": "sans-serif",
    "source": "@fontsource/montserrat-alternates 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/montserrat-alternates/montserrat-alternates-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/montserrat-alternates/montserrat-alternates-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/montserrat-alternates/LICENSE.txt"
  },
  "Mozilla Headline": {
    "slug": "mozilla-headline",
    "category": "sans-serif",
    "source": "@fontsource-variable/mozilla-headline 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/mozilla-headline/mozilla-headline-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/mozilla-headline/LICENSE.txt"
  },
  "Mozilla Text": {
    "slug": "mozilla-text",
    "category": "sans-serif",
    "source": "@fontsource-variable/mozilla-text 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/mozilla-text/mozilla-text-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/mozilla-text/LICENSE.txt"
  },
  "Mukta": {
    "slug": "mukta",
    "category": "sans-serif",
    "source": "@fontsource/mukta 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/mukta/mukta-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/mukta/mukta-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/mukta/LICENSE.txt"
  },
  "Mulish": {
    "slug": "mulish",
    "category": "sans-serif",
    "source": "@fontsource-variable/mulish 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/mulish/mulish-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/mulish/LICENSE.txt"
  },
  "National Park": {
    "slug": "national-park",
    "category": "sans-serif",
    "source": "@fontsource-variable/national-park 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/national-park/national-park-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/national-park/LICENSE.txt"
  },
  "Newsreader": {
    "slug": "newsreader",
    "category": "serif",
    "source": "@fontsource-variable/newsreader 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/newsreader/newsreader-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/newsreader/LICENSE.txt"
  },
  "Noto Sans": {
    "slug": "noto-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/noto-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/noto-sans/noto-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/noto-sans/LICENSE.txt"
  },
  "Noto Sans Display": {
    "slug": "noto-sans-display",
    "category": "sans-serif",
    "source": "@fontsource-variable/noto-sans-display 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/noto-sans-display/noto-sans-display-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/noto-sans-display/LICENSE.txt"
  },
  "Noto Serif Display": {
    "slug": "noto-serif-display",
    "category": "serif",
    "source": "@fontsource-variable/noto-serif-display 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/noto-serif-display/noto-serif-display-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/noto-serif-display/LICENSE.txt"
  },
  "Nunito": {
    "slug": "nunito",
    "category": "sans-serif",
    "source": "@fontsource-variable/nunito 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/nunito/nunito-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/nunito/LICENSE.txt"
  },
  "Nunito Sans": {
    "slug": "nunito-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/nunito-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/nunito-sans/nunito-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/nunito-sans/LICENSE.txt"
  },
  "Onest": {
    "slug": "onest",
    "category": "sans-serif",
    "source": "@fontsource-variable/onest 5.3.1",
    "files": [
      {
        "file": "/fonts/templates/onest/onest-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/onest/LICENSE.txt"
  },
  "Open Sans": {
    "slug": "open-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/open-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/open-sans/open-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/open-sans/LICENSE.txt"
  },
  "Oswald": {
    "slug": "oswald",
    "category": "sans-serif",
    "source": "@fontsource-variable/oswald 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/oswald/oswald-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/oswald/LICENSE.txt"
  },
  "Outfit": {
    "slug": "outfit",
    "category": "sans-serif",
    "source": "@fontsource-variable/outfit 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/outfit/outfit-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/outfit/LICENSE.txt"
  },
  "Overpass": {
    "slug": "overpass",
    "category": "sans-serif",
    "source": "@fontsource-variable/overpass 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/overpass/overpass-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/overpass/LICENSE.txt"
  },
  "Overpass Mono": {
    "slug": "overpass-mono",
    "category": "monospace",
    "source": "@fontsource-variable/overpass-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/overpass-mono/overpass-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/overpass-mono/LICENSE.txt"
  },
  "PT Mono": {
    "slug": "pt-mono",
    "category": "monospace",
    "source": "@fontsource/pt-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/pt-mono/pt-mono-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/pt-mono/LICENSE.txt"
  },
  "PT Sans": {
    "slug": "pt-sans",
    "category": "sans-serif",
    "source": "@fontsource/pt-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/pt-sans/pt-sans-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/pt-sans/pt-sans-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/pt-sans/LICENSE.txt"
  },
  "Parkinsans": {
    "slug": "parkinsans",
    "category": "sans-serif",
    "source": "@fontsource-variable/parkinsans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/parkinsans/parkinsans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/parkinsans/LICENSE.txt"
  },
  "Pathway Extreme": {
    "slug": "pathway-extreme",
    "category": "sans-serif",
    "source": "@fontsource-variable/pathway-extreme 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/pathway-extreme/pathway-extreme-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/pathway-extreme/LICENSE.txt"
  },
  "Petrona": {
    "slug": "petrona",
    "category": "serif",
    "source": "@fontsource-variable/petrona 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/petrona/petrona-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/petrona/LICENSE.txt"
  },
  "Philosopher": {
    "slug": "philosopher",
    "category": "sans-serif",
    "source": "@fontsource/philosopher 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/philosopher/philosopher-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/philosopher/philosopher-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/philosopher/LICENSE.txt"
  },
  "Pixelify Sans": {
    "slug": "pixelify-sans",
    "category": "display",
    "source": "@fontsource-variable/pixelify-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/pixelify-sans/pixelify-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/pixelify-sans/LICENSE.txt"
  },
  "Playfair": {
    "slug": "playfair",
    "category": "serif",
    "source": "@fontsource-variable/playfair 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/playfair/playfair-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/playfair/LICENSE.txt"
  },
  "Playfair Display": {
    "slug": "playfair-display",
    "category": "serif",
    "source": "@fontsource-variable/playfair-display 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/playfair-display/playfair-display-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/playfair-display/LICENSE.txt"
  },
  "Plus Jakarta Sans": {
    "slug": "plus-jakarta-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/plus-jakarta-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/plus-jakarta-sans/plus-jakarta-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/plus-jakarta-sans/LICENSE.txt"
  },
  "Pontano Sans": {
    "slug": "pontano-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/pontano-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/pontano-sans/pontano-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/pontano-sans/LICENSE.txt"
  },
  "Poppins": {
    "slug": "poppins",
    "category": "sans-serif",
    "source": "@fontsource/poppins 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/poppins/poppins-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/poppins/poppins-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/poppins/LICENSE.txt"
  },
  "Prompt": {
    "slug": "prompt",
    "category": "sans-serif",
    "source": "@fontsource/prompt 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/prompt/prompt-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/prompt/prompt-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/prompt/LICENSE.txt"
  },
  "Proza Libre": {
    "slug": "proza-libre",
    "category": "sans-serif",
    "source": "@fontsource/proza-libre 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/proza-libre/proza-libre-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/proza-libre/proza-libre-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/proza-libre/LICENSE.txt"
  },
  "Public Sans": {
    "slug": "public-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/public-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/public-sans/public-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/public-sans/LICENSE.txt"
  },
  "Quicksand": {
    "slug": "quicksand",
    "category": "sans-serif",
    "source": "@fontsource-variable/quicksand 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/quicksand/quicksand-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/quicksand/LICENSE.txt"
  },
  "Radio Canada": {
    "slug": "radio-canada",
    "category": "sans-serif",
    "source": "@fontsource-variable/radio-canada 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/radio-canada/radio-canada-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/radio-canada/LICENSE.txt"
  },
  "Radio Canada Big": {
    "slug": "radio-canada-big",
    "category": "sans-serif",
    "source": "@fontsource-variable/radio-canada-big 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/radio-canada-big/radio-canada-big-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/radio-canada-big/LICENSE.txt"
  },
  "Raleway": {
    "slug": "raleway",
    "category": "sans-serif",
    "source": "@fontsource-variable/raleway 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/raleway/raleway-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/raleway/LICENSE.txt"
  },
  "Readex Pro": {
    "slug": "readex-pro",
    "category": "sans-serif",
    "source": "@fontsource-variable/readex-pro 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/readex-pro/readex-pro-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/readex-pro/LICENSE.txt"
  },
  "Red Hat Display": {
    "slug": "red-hat-display",
    "category": "sans-serif",
    "source": "@fontsource-variable/red-hat-display 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/red-hat-display/red-hat-display-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/red-hat-display/LICENSE.txt"
  },
  "Red Hat Mono": {
    "slug": "red-hat-mono",
    "category": "monospace",
    "source": "@fontsource-variable/red-hat-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/red-hat-mono/red-hat-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/red-hat-mono/LICENSE.txt"
  },
  "Red Hat Text": {
    "slug": "red-hat-text",
    "category": "sans-serif",
    "source": "@fontsource-variable/red-hat-text 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/red-hat-text/red-hat-text-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/red-hat-text/LICENSE.txt"
  },
  "Reddit Mono": {
    "slug": "reddit-mono",
    "category": "monospace",
    "source": "@fontsource-variable/reddit-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/reddit-mono/reddit-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/reddit-mono/LICENSE.txt"
  },
  "Reddit Sans": {
    "slug": "reddit-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/reddit-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/reddit-sans/reddit-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/reddit-sans/LICENSE.txt"
  },
  "Rethink Sans": {
    "slug": "rethink-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/rethink-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/rethink-sans/rethink-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/rethink-sans/LICENSE.txt"
  },
  "Roboto": {
    "slug": "roboto",
    "category": "sans-serif",
    "source": "@fontsource-variable/roboto 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/roboto/roboto-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/roboto/LICENSE.txt"
  },
  "Roboto Flex": {
    "slug": "roboto-flex",
    "category": "sans-serif",
    "source": "@fontsource-variable/roboto-flex 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/roboto-flex/roboto-flex-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/roboto-flex/LICENSE.txt"
  },
  "Roboto Mono": {
    "slug": "roboto-mono",
    "category": "monospace",
    "source": "@fontsource-variable/roboto-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/roboto-mono/roboto-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/roboto-mono/LICENSE.txt"
  },
  "Roboto Slab": {
    "slug": "roboto-slab",
    "category": "serif",
    "source": "@fontsource-variable/roboto-slab 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/roboto-slab/roboto-slab-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/roboto-slab/LICENSE.txt"
  },
  "Rosario": {
    "slug": "rosario",
    "category": "sans-serif",
    "source": "@fontsource-variable/rosario 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/rosario/rosario-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/rosario/LICENSE.txt"
  },
  "Rubik": {
    "slug": "rubik",
    "category": "sans-serif",
    "source": "@fontsource-variable/rubik 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/rubik/rubik-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/rubik/LICENSE.txt"
  },
  "SUSE": {
    "slug": "suse",
    "category": "sans-serif",
    "source": "@fontsource-variable/suse 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/suse/suse-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/suse/LICENSE.txt"
  },
  "Saira": {
    "slug": "saira",
    "category": "sans-serif",
    "source": "@fontsource-variable/saira 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/saira/saira-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/saira/LICENSE.txt"
  },
  "Satisfy": {
    "slug": "satisfy",
    "category": "handwriting",
    "source": "@fontsource/satisfy 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/satisfy/satisfy-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/satisfy/LICENSE.txt"
  },
  "Schibsted Grotesk": {
    "slug": "schibsted-grotesk",
    "category": "sans-serif",
    "source": "@fontsource-variable/schibsted-grotesk 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/schibsted-grotesk/schibsted-grotesk-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/schibsted-grotesk/LICENSE.txt"
  },
  "Sen": {
    "slug": "sen",
    "category": "sans-serif",
    "source": "@fontsource-variable/sen 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/sen/sen-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/sen/LICENSE.txt"
  },
  "Share Tech Mono": {
    "slug": "share-tech-mono",
    "category": "monospace",
    "source": "@fontsource/share-tech-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/share-tech-mono/share-tech-mono-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/share-tech-mono/LICENSE.txt"
  },
  "Signika": {
    "slug": "signika",
    "category": "sans-serif",
    "source": "@fontsource-variable/signika 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/signika/signika-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/signika/LICENSE.txt"
  },
  "Sofia Sans": {
    "slug": "sofia-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/sofia-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/sofia-sans/sofia-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/sofia-sans/LICENSE.txt"
  },
  "Sofia Sans Extra Condensed": {
    "slug": "sofia-sans-extra-condensed",
    "category": "sans-serif",
    "source": "@fontsource-variable/sofia-sans-extra-condensed 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/sofia-sans-extra-condensed/sofia-sans-extra-condensed-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/sofia-sans-extra-condensed/LICENSE.txt"
  },
  "Sofia Sans Semi Condensed": {
    "slug": "sofia-sans-semi-condensed",
    "category": "sans-serif",
    "source": "@fontsource-variable/sofia-sans-semi-condensed 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/sofia-sans-semi-condensed/sofia-sans-semi-condensed-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/sofia-sans-semi-condensed/LICENSE.txt"
  },
  "Sometype Mono": {
    "slug": "sometype-mono",
    "category": "monospace",
    "source": "@fontsource-variable/sometype-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/sometype-mono/sometype-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/sometype-mono/LICENSE.txt"
  },
  "Sora": {
    "slug": "sora",
    "category": "sans-serif",
    "source": "@fontsource-variable/sora 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/sora/sora-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/sora/LICENSE.txt"
  },
  "Source Code Pro": {
    "slug": "source-code-pro",
    "category": "monospace",
    "source": "@fontsource-variable/source-code-pro 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/source-code-pro/source-code-pro-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/source-code-pro/LICENSE.txt"
  },
  "Source Sans 3": {
    "slug": "source-sans-3",
    "category": "sans-serif",
    "source": "@fontsource-variable/source-sans-3 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/source-sans-3/source-sans-3-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/source-sans-3/LICENSE.txt"
  },
  "Source Serif 4": {
    "slug": "source-serif-4",
    "category": "serif",
    "source": "@fontsource-variable/source-serif-4 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/source-serif-4/source-serif-4-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/source-serif-4/LICENSE.txt"
  },
  "Space Grotesk": {
    "slug": "space-grotesk",
    "category": "sans-serif",
    "source": "@fontsource-variable/space-grotesk 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/space-grotesk/space-grotesk-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/space-grotesk/LICENSE.txt"
  },
  "Space Mono": {
    "slug": "space-mono",
    "category": "monospace",
    "source": "@fontsource/space-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/space-mono/space-mono-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/space-mono/space-mono-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/space-mono/LICENSE.txt"
  },
  "Special Gothic": {
    "slug": "special-gothic",
    "category": "sans-serif",
    "source": "@fontsource-variable/special-gothic 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/special-gothic/special-gothic-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/special-gothic/LICENSE.txt"
  },
  "Spectral": {
    "slug": "spectral",
    "category": "serif",
    "source": "@fontsource/spectral 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/spectral/spectral-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/spectral/spectral-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/spectral/LICENSE.txt"
  },
  "Spline Sans": {
    "slug": "spline-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/spline-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/spline-sans/spline-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/spline-sans/LICENSE.txt"
  },
  "Spline Sans Mono": {
    "slug": "spline-sans-mono",
    "category": "monospace",
    "source": "@fontsource-variable/spline-sans-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/spline-sans-mono/spline-sans-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/spline-sans-mono/LICENSE.txt"
  },
  "Syne": {
    "slug": "syne",
    "category": "sans-serif",
    "source": "@fontsource-variable/syne 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/syne/syne-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/syne/LICENSE.txt"
  },
  "TASA Orbiter": {
    "slug": "tasa-orbiter",
    "category": "sans-serif",
    "source": "@fontsource-variable/tasa-orbiter 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/tasa-orbiter/tasa-orbiter-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/tasa-orbiter/LICENSE.txt"
  },
  "Teachers": {
    "slug": "teachers",
    "category": "sans-serif",
    "source": "@fontsource-variable/teachers 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/teachers/teachers-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/teachers/LICENSE.txt"
  },
  "TikTok Sans": {
    "slug": "tiktok-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/tiktok-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/tiktok-sans/tiktok-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/tiktok-sans/LICENSE.txt"
  },
  "Tomorrow": {
    "slug": "tomorrow",
    "category": "sans-serif",
    "source": "@fontsource/tomorrow 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/tomorrow/tomorrow-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/tomorrow/tomorrow-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/tomorrow/LICENSE.txt"
  },
  "Ubuntu Mono": {
    "slug": "ubuntu-mono",
    "category": "monospace",
    "source": "@fontsource/ubuntu-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/ubuntu-mono/ubuntu-mono-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/ubuntu-mono/ubuntu-mono-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/ubuntu-mono/LICENSE.txt"
  },
  "Ubuntu Sans": {
    "slug": "ubuntu-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/ubuntu-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/ubuntu-sans/ubuntu-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/ubuntu-sans/LICENSE.txt"
  },
  "Ubuntu Sans Mono": {
    "slug": "ubuntu-sans-mono",
    "category": "monospace",
    "source": "@fontsource-variable/ubuntu-sans-mono 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/ubuntu-sans-mono/ubuntu-sans-mono-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/ubuntu-sans-mono/LICENSE.txt"
  },
  "Unbounded": {
    "slug": "unbounded",
    "category": "sans-serif",
    "source": "@fontsource-variable/unbounded 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/unbounded/unbounded-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/unbounded/LICENSE.txt"
  },
  "UnifrakturMaguntia": {
    "slug": "unifrakturmaguntia",
    "category": "display",
    "source": "@fontsource/unifrakturmaguntia 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/unifrakturmaguntia/unifrakturmaguntia-latin-400-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/unifrakturmaguntia/LICENSE.txt"
  },
  "Urbanist": {
    "slug": "urbanist",
    "category": "sans-serif",
    "source": "@fontsource-variable/urbanist 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/urbanist/urbanist-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/urbanist/LICENSE.txt"
  },
  "Winky Sans": {
    "slug": "winky-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/winky-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/winky-sans/winky-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/winky-sans/LICENSE.txt"
  },
  "Wix Madefor Display": {
    "slug": "wix-madefor-display",
    "category": "sans-serif",
    "source": "@fontsource-variable/wix-madefor-display 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/wix-madefor-display/wix-madefor-display-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/wix-madefor-display/LICENSE.txt"
  },
  "Wix Madefor Text": {
    "slug": "wix-madefor-text",
    "category": "sans-serif",
    "source": "@fontsource-variable/wix-madefor-text 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/wix-madefor-text/wix-madefor-text-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/wix-madefor-text/LICENSE.txt"
  },
  "Work Sans": {
    "slug": "work-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/work-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/work-sans/work-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/work-sans/LICENSE.txt"
  },
  "Ysabeau Office": {
    "slug": "ysabeau-office",
    "category": "sans-serif",
    "source": "@fontsource-variable/ysabeau-office 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/ysabeau-office/ysabeau-office-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/ysabeau-office/LICENSE.txt"
  },
  "Zalando Sans": {
    "slug": "zalando-sans",
    "category": "sans-serif",
    "source": "@fontsource-variable/zalando-sans 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/zalando-sans/zalando-sans-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/zalando-sans/LICENSE.txt"
  },
  "Zalando Sans Expanded": {
    "slug": "zalando-sans-expanded",
    "category": "sans-serif",
    "source": "@fontsource-variable/zalando-sans-expanded 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/zalando-sans-expanded/zalando-sans-expanded-latin-wght-normal.woff2",
        "weight": "400"
      }
    ],
    "licence": "/fonts/templates/zalando-sans-expanded/LICENSE.txt"
  },
  "Zen Kaku Gothic New": {
    "slug": "zen-kaku-gothic-new",
    "category": "sans-serif",
    "source": "@fontsource/zen-kaku-gothic-new 5.3.0",
    "files": [
      {
        "file": "/fonts/templates/zen-kaku-gothic-new/zen-kaku-gothic-new-latin-400-normal.woff2",
        "weight": "400"
      },
      {
        "file": "/fonts/templates/zen-kaku-gothic-new/zen-kaku-gothic-new-latin-700-normal.woff2",
        "weight": "700"
      }
    ],
    "licence": "/fonts/templates/zen-kaku-gothic-new/LICENSE.txt"
  }
};
