import { useMemo } from 'react';
import type { BuilderState } from '../generation/session.ts';
import { buildPreviewDocument } from '../generation/preview.ts';
import type { PreviewSandbox } from '../generation/use-preview-sandbox.ts';

function describeStatus(status: PreviewSandbox['status']): string | null {
  if (!status) return null;
  switch (status.status) {
    case 'queued':
      return `Queued for a sandbox (position ${status.position})…`;
    case 'ready-to-start':
      return 'Waiting for a sandbox…';
    case 'installing':
      return 'Installing dependencies…';
    case 'starting':
      return 'Starting the dev server…';
    case 'ready':
      return null; // The frame itself is the status, once it is up.
    case 'failed':
      return status.error;
  }
}

/**
 * Real sandbox execution (docs/decisions.md L7-L11, ADR-0004) once it is
 * running, otherwise the same local mock this panel has always shown. The
 * two are mutually exclusive on screen -- a stale mock sitting next to a
 * live, installed copy of the same project would only invite confusion
 * about which one is actually being looked at.
 */
export function PreviewPanel({
  state,
  sandbox,
}: {
  state: BuilderState;
  sandbox: PreviewSandbox;
}) {
  const mockDocument = useMemo(() => {
    if (!state.acceptedBrief || !state.acceptedSnapshot) return null;
    return buildPreviewDocument(state.acceptedBrief, state.acceptedSnapshot);
  }, [state.acceptedBrief, state.acceptedSnapshot]);

  const statusMessage = describeStatus(sandbox.status);
  const running = sandbox.status !== null && sandbox.status.status !== 'failed';

  return (
    <div className="preview">
      {sandbox.status?.status === 'ready' ? (
        <iframe
          className="preview__frame"
          title="Sandbox preview of the generated application"
          src={sandbox.status.url}
        />
      ) : (
        <>
          <p className="preview__notice">
            <strong>Local mock preview.</strong> This is static HTML assembled
            from the accepted plan and stylesheet, rendered in a fully
            restricted frame. No dependencies are installed and no generated
            code is executed here — use "Run in sandbox" below for a real,
            installed copy of the project.
          </p>
          {mockDocument ? (
            <iframe
              className="preview__frame"
              title="Local mock preview of the generated application"
              srcDoc={mockDocument}
              sandbox=""
            />
          ) : state.acceptedSnapshot ? (
            <p className="empty">
              This checkpoint was generated by a model, so there is no local
              mock to render — the mock only knows the deterministic
              planner&apos;s own structure. Use the Code tab to inspect the
              files, or "Run in sandbox" below for a real preview.
            </p>
          ) : (
            <p className="empty">Accept a checkpoint to see the preview.</p>
          )}
        </>
      )}

      {state.acceptedSnapshot ? (
        <>
          <div className="preview__sandbox">
            <button
              type="button"
              className="chip"
              disabled={sandbox.pending}
              onClick={() => sandbox.run(state.acceptedSnapshot!.files)}
            >
              {sandbox.status?.status === 'ready'
                ? 'Restart in sandbox'
                : 'Run in sandbox'}
            </button>
            {running ? (
              <button
                type="button"
                className="chip"
                disabled={sandbox.pending}
                onClick={() => sandbox.stop()}
              >
                Stop
              </button>
            ) : null}
            {sandbox.status?.status === 'ready' ? (
              <span className="preview__expiry">
                Expires around{' '}
                {new Date(sandbox.status.expiresAt).toLocaleTimeString()}
              </span>
            ) : null}
          </div>
          {statusMessage ? (
            <p
              className={`pane-note${sandbox.status?.status === 'failed' ? ' pane-note--error' : ''}`}
              role={sandbox.status?.status === 'failed' ? 'alert' : undefined}
            >
              {statusMessage}
            </p>
          ) : null}
        </>
      ) : null}
    </div>
  );
}
