import { useMemo } from 'react';
import type { BuilderState } from '../generation/session.ts';
import { buildPreviewDocument } from '../generation/preview.ts';

export function PreviewPanel({ state }: { state: BuilderState }) {
  const document = useMemo(() => {
    if (!state.acceptedBrief || !state.acceptedSnapshot) return null;
    return buildPreviewDocument(state.acceptedBrief, state.acceptedSnapshot);
  }, [state.acceptedBrief, state.acceptedSnapshot]);

  return (
    <div className="preview">
      <p className="preview__notice">
        <strong>Local mock preview.</strong> This is static HTML assembled from
        the accepted plan and stylesheet, rendered in a fully restricted frame.
        No dependencies are installed and no generated code is executed —
        sandbox execution is not implemented yet.
      </p>
      {document ? (
        <iframe
          className="preview__frame"
          title="Local mock preview of the generated application"
          srcDoc={document}
          sandbox=""
        />
      ) : state.acceptedSnapshot ? (
        <p className="empty">
          This checkpoint was generated by a model, so there is no local mock to
          render — the mock only knows the deterministic planner&apos;s own
          structure. Use the Code tab to inspect the files. A running preview
          arrives with sandbox execution.
        </p>
      ) : (
        <p className="empty">Accept a checkpoint to see the preview.</p>
      )}
    </div>
  );
}
