/**
 * The design template catalog: app and website designs and SaaS screen
 * patterns, each with a build prompt, and each one's palette and type
 * pairing as a reusable inspiration style (docs/decisions.md, D83 to D87,
 * D107 to D110).
 *
 * The data is `../data/design-templates.ts`, generated by
 * `bin/import-design-catalog.ts` from two batches in Drummond-IT/designs-v1:
 * `design-prompt-catalog/` and `saas-screen-patterns/`. Their words are the
 * catalogs' own, with one change of punctuation (D87); what is vibld's is
 * the shape: `kind` and `useCase` from vibld.com's own taxonomy,
 * `mergedInto` for an entry shown on one of vibld's examples or on another
 * design, and `style.tokens`, the palette on vibld's fifteen colour tokens
 * in the shape a style preset's `tokens` take.
 *
 * A screen pattern (`format: 'screen'`) is one app screen, such as a
 * dashboard, settings page or empty state, that a template composes into
 * its brief (`composeBrief`, D110).
 *
 * Imported by its own subpath, `@vibld/ai/design-templates`, and never from
 * the package index, so the catalog's megabytes reach only the code that
 * asks for it.
 */
import catalog from '../data/design-templates.ts';
import type { TypeFace } from '../data/design-template-type.ts';
import type { StyleTokens } from './style-presets.ts';
import { screenSections } from './screen-patterns.ts';

export type { TypeFace, TypeRole } from '../data/design-template-type.ts';

/** vibld.com's use cases (`apps/marketing/app/use-cases.ts`). */
export type DesignUseCase =
  'small-business' | 'portfolio' | 'saas-landing' | 'events' | 'tools';

export const DESIGN_USE_CASES: readonly DesignUseCase[] = [
  'small-business',
  'portfolio',
  'saas-landing',
  'events',
  'tools',
];

export type DesignFormat = 'design' | 'page' | 'screen' | 'section';

/**
 * Where each batch of templates came from (D106), so a gallery can sort by
 * what is new and say where a design came from.
 */
export const DESIGN_BATCHES = {
  'design-catalog': {
    name: 'Design catalog',
    repository: 'Drummond-IT/designs-v1',
    path: 'design-prompt-catalog',
    addedOn: '2026-09-30',
  },
  'saas-screen-patterns': {
    name: 'SaaS screen patterns',
    repository: 'Drummond-IT/designs-v1',
    path: 'saas-screen-patterns',
    addedOn: '2026-09-30',
  },
} as const satisfies Record<
  string,
  { name: string; repository: string; path: string; addedOn: string }
>;

export interface DesignFont {
  /** The face as the design names it. */
  asWritten: string;
  family: string;
  onGoogleFonts: boolean;
  /** The Google family a project loads when `family` is not on Google Fonts. */
  substitute?: string;
}

export interface DesignContrastCheck {
  use: string;
  fg?: string;
  bg?: string;
  ratio?: number;
  target?: number;
  exempt?: unknown;
}

export interface InspirationStyle {
  mood: string;
  imagery: string;
  spacing: string;
  /** The palette as drawn, with the catalog's own role names. */
  palette: readonly { role: string; hex: string }[];
  typography: { display: string; body: string; notes?: string };
  fonts: { display: DesignFont; body: DesignFont };
  /**
   * The design's own typefaces (D103): one family or several, each with
   * the role it plays. No two designs share a set.
   */
  typeSet: readonly TypeFace[];
  /** Why this set suits this design. */
  typeWhy: string;
  /** Every pair the catalog measured, as it recorded them. */
  contrastChecks: readonly DesignContrastCheck[];
  /** The palette and type on vibld's tokens, ready for `tokenCss`. */
  tokens: StyleTokens;
  /** Tokens no swatch could fill, solved rather than drawn. */
  derived: readonly (keyof StyleTokens['colors'])[];
}

export interface DesignTemplate {
  id: string;
  name: string;
  /** One line: what it is. */
  summary: string;
  kind: 'site' | 'app';
  useCase: DesignUseCase;
  /** The catalog's own category, kept beside the use case. */
  category: string;
  complexity: string;
  /**
   * What it is (D106): a whole product's design, or a single page, screen
   * or section. A SaaS screen pattern is a `screen`.
   */
  format: DesignFormat;
  /** The batch it arrived in (`DESIGN_BATCHES`). */
  batch: string;
  /** ISO date it was added to vibld. */
  addedOn: string;
  /**
   * Set when this is the same product as one of vibld's own examples (D85)
   * or as another design in the catalog (D107): it is shown there, not
   * listed on its own.
   */
  mergedInto?: {
    collection: 'examples' | 'templates';
    slug: string;
    reason: string;
  };
  purpose: string;
  audience: readonly string[];
  layout: readonly string[];
  components: readonly string[];
  interactions: readonly string[];
  dataModel: readonly string[];
  stack: readonly string[];
  /** SaaS screen patterns only: the kinds of screen it is (D110). */
  screenTypes?: readonly string[];
  /** SaaS screen patterns only: the UI patterns it is built from. */
  patterns?: readonly string[];
  /** SaaS screen patterns only: every state it is designed for. */
  states?: readonly string[];
  /** SaaS screen patterns only: its guardrails, as the catalog wrote them. */
  guardrails?: {
    ux: readonly string[];
    accessibility: readonly string[];
    security: readonly string[];
  };
  style: InspirationStyle;
  /** Ten `###` sections, Goal to Guardrails, as the catalog wrote them. */
  buildPrompt: string;
}

export interface DesignSource {
  batch: DesignBatch;
  repository: string;
  path: string;
  /** The last commit that changed it when it was imported. */
  commit: string;
  updated: string;
  /** The rules every build prompt in it assumes, as its catalog wrote them. */
  baseline: string;
}

export type DesignBatch = keyof typeof DESIGN_BATCHES;

interface CatalogFile {
  sources: DesignSource[];
  templates: DesignTemplate[];
}

const data = catalog as unknown as CatalogFile;

/** Where each batch came from, in the order they arrived. */
export const DESIGN_SOURCES: readonly DesignSource[] = data.sources;

/** The first batch, the design prompt catalog. */
export const DESIGN_CATALOG_SOURCE = data.sources[0]!;

/** The rules the design prompt catalog's build prompts assume. */
export const DESIGN_BASELINE: string = DESIGN_CATALOG_SOURCE.baseline;

/** The baseline a design's build prompt assumes: its own batch's. */
export function baselineFor(template: Pick<DesignTemplate, 'batch'>): string {
  return (
    DESIGN_SOURCES.find((s) => s.batch === template.batch)?.baseline ??
    DESIGN_BASELINE
  );
}

export const DESIGN_TEMPLATES: readonly DesignTemplate[] = data.templates;

/** The ten sections every build prompt has, in order. */
export const BUILD_PROMPT_SECTIONS = [
  'Goal',
  'Stack',
  'Pages & layout',
  'Design system',
  'Components & interactions',
  'Data & state',
  'Accessibility',
  'Security',
  'Performance & SEO',
  'Guardrails',
] as const;

const BY_ID = new Map(DESIGN_TEMPLATES.map((t) => [t.id, t]));

export function findDesignTemplate(id: string): DesignTemplate | undefined {
  return BY_ID.get(id);
}

export function isDesignTemplateId(id: unknown): id is string {
  return typeof id === 'string' && BY_ID.has(id);
}

/**
 * The templates a gallery lists: every design except those merged into one
 * of vibld's examples or into another design, which the gallery shows there
 * instead.
 */
export function listedDesignTemplates(filter?: {
  useCase?: DesignUseCase;
  kind?: 'site' | 'app';
  format?: DesignFormat;
}): DesignTemplate[] {
  return DESIGN_TEMPLATES.filter(
    (t) =>
      !t.mergedInto &&
      (!filter?.useCase || t.useCase === filter.useCase) &&
      (!filter?.kind || t.kind === filter.kind) &&
      (!filter?.format || t.format === filter.format),
  );
}

/** The designs merged into one of vibld's examples, by the example's slug. */
export function designsForExample(slug: string): DesignTemplate[] {
  return DESIGN_TEMPLATES.filter(
    (t) =>
      t.mergedInto?.collection === 'examples' && t.mergedInto.slug === slug,
  );
}

/** Other designs for the same product, shown on this one (D107). */
export function designsMergedInto(id: string): DesignTemplate[] {
  return DESIGN_TEMPLATES.filter(
    (t) => t.mergedInto?.collection === 'templates' && t.mergedInto.slug === id,
  );
}

/** Every screen pattern (D110). */
export const SCREEN_PATTERNS: readonly DesignTemplate[] =
  DESIGN_TEMPLATES.filter((t) => t.format === 'screen');

/**
 * Every screen type, as the catalog groups its screens: a screen's category
 * (dashboard, settings, empty-state...). Its `screenTypes` may add others.
 */
export const SCREEN_TYPES: readonly string[] = [
  ...new Set(SCREEN_PATTERNS.map((t) => t.category)),
].sort();

/**
 * What a coding agent is given to build a template, as the catalog says to
 * use it: its batch's baseline first, then the template's build prompt.
 */
export function designBrief(id: string): string | undefined {
  const template = findDesignTemplate(id);
  if (!template) return undefined;
  return `${baselineFor(template).trim()}\n\n## ${template.name}\n\n${template.buildPrompt.trim()}\n`;
}

/**
 * A template's brief with screen patterns composed into it (D110): the
 * brief, then each screen to build inside the same project, in the
 * template's own design system. Unknown screen ids are left out, and so are
 * screens past `maxChars` for the whole brief.
 */
export function composeBrief(
  id: string,
  screenIds: readonly string[],
  maxChars = Number.POSITIVE_INFINITY,
): string | undefined {
  const brief = designBrief(id);
  if (brief === undefined) return undefined;
  const screens = screenSections(screenIds, maxChars - brief.length - 1);
  return screens ? `${brief}\n${screens}` : brief;
}
