/**
 * The design template catalog: 207 app and website designs, each with a
 * build prompt, and each design's palette and type pairing as a reusable
 * inspiration style (docs/decisions.md, D83 to D87).
 *
 * The data is `../data/design-templates.ts`, generated by
 * `bin/import-design-catalog.ts` from Drummond-IT/designs-v1's
 * `design-prompt-catalog/`. Its words are the catalog's own, with one change
 * of punctuation (D87); what is vibld's is the shape: `kind` and `useCase`
 * from vibld.com's own taxonomy, `mergedInto` for a design that is one of
 * vibld's examples, and `style.tokens`, the palette on vibld's fifteen
 * colour tokens in the shape a style preset's `tokens` take.
 *
 * Imported by its own subpath, `@vibld/ai/design-templates`, and never from
 * the package index, so the catalog's 2.6 MB reaches only the code that
 * asks for it.
 */
import catalog from '../data/design-templates.ts';
import type { TypeFace } from '../data/design-template-type.ts';
import type { StyleTokens } from './style-presets.ts';

export type { TypeFace, TypeRole } from '../data/design-template-type.ts';

/** vibld.com's use cases (`apps/marketing/app/use-cases.ts`). */
export type DesignUseCase =
  'small-business' | 'portfolio' | 'saas-landing' | 'events' | 'tools';

export const DESIGN_USE_CASES: readonly DesignUseCase[] = [
  'small-business',
  'portfolio',
  'saas-landing',
  'events',
  'tools',
];

export type DesignFormat = 'design' | 'page' | 'screen' | 'section';

/**
 * Where each batch of templates came from (D106), so a gallery can sort by
 * what is new and say where a design came from.
 */
export const DESIGN_BATCHES = {
  'design-catalog': {
    name: 'Design catalog',
    repository: 'Drummond-IT/designs-v1',
    path: 'design-prompt-catalog',
    addedOn: '2026-09-30',
  },
} as const satisfies Record<
  string,
  { name: string; repository: string; path: string; addedOn: string }
>;

export interface DesignFont {
  /** The face as the design names it. */
  asWritten: string;
  family: string;
  onGoogleFonts: boolean;
  /** The Google family a project loads when `family` is not on Google Fonts. */
  substitute?: string;
}

export interface DesignContrastCheck {
  use: string;
  fg?: string;
  bg?: string;
  ratio?: number;
  target?: number;
  exempt?: unknown;
}

export interface InspirationStyle {
  mood: string;
  imagery: string;
  spacing: string;
  /** The palette as drawn, with the catalog's own role names. */
  palette: readonly { role: string; hex: string }[];
  typography: { display: string; body: string; notes?: string };
  fonts: { display: DesignFont; body: DesignFont };
  /**
   * The design's own typefaces (D103): one family or several, each with
   * the role it plays. No two designs share a set.
   */
  typeSet: readonly TypeFace[];
  /** Why this set suits this design. */
  typeWhy: string;
  /** Every pair the catalog measured, as it recorded them. */
  contrastChecks: readonly DesignContrastCheck[];
  /** The palette and type on vibld's tokens, ready for `tokenCss`. */
  tokens: StyleTokens;
  /** Tokens no swatch could fill, solved rather than drawn. */
  derived: readonly (keyof StyleTokens['colors'])[];
}

export interface DesignTemplate {
  id: string;
  name: string;
  /** One line: what it is. */
  summary: string;
  kind: 'site' | 'app';
  useCase: DesignUseCase;
  /** The catalog's own category, kept beside the use case. */
  category: string;
  complexity: string;
  /**
   * What it is (D106): a whole product's design, or a single page, screen
   * or section. Every design in this catalog is `design`.
   */
  format: DesignFormat;
  /** The batch it arrived in (`DESIGN_BATCHES`). */
  batch: string;
  /** ISO date it was added to vibld. */
  addedOn: string;
  /** Set when this design is one of vibld's own examples. */
  mergedInto?: { collection: 'examples'; slug: string; reason: string };
  purpose: string;
  audience: readonly string[];
  layout: readonly string[];
  components: readonly string[];
  interactions: readonly string[];
  dataModel: readonly string[];
  stack: readonly string[];
  style: InspirationStyle;
  /** Ten `###` sections, Goal to Guardrails, as the catalog wrote them. */
  buildPrompt: string;
}

interface CatalogFile {
  source: { repository: string; path: string; commit: string; updated: string };
  baseline: string;
  templates: DesignTemplate[];
}

const data = catalog as unknown as CatalogFile;

export const DESIGN_CATALOG_SOURCE = data.source;

/** The rules every build prompt assumes, as the catalog wrote them. */
export const DESIGN_BASELINE: string = data.baseline;

export const DESIGN_TEMPLATES: readonly DesignTemplate[] = data.templates;

/** The ten sections every build prompt has, in order. */
export const BUILD_PROMPT_SECTIONS = [
  'Goal',
  'Stack',
  'Pages & layout',
  'Design system',
  'Components & interactions',
  'Data & state',
  'Accessibility',
  'Security',
  'Performance & SEO',
  'Guardrails',
] as const;

const BY_ID = new Map(DESIGN_TEMPLATES.map((t) => [t.id, t]));

export function findDesignTemplate(id: string): DesignTemplate | undefined {
  return BY_ID.get(id);
}

export function isDesignTemplateId(id: unknown): id is string {
  return typeof id === 'string' && BY_ID.has(id);
}

/**
 * The templates a gallery lists: every design except those merged into one
 * of vibld's examples, which the gallery shows on that example instead.
 */
export function listedDesignTemplates(filter?: {
  useCase?: DesignUseCase;
  kind?: 'site' | 'app';
}): DesignTemplate[] {
  return DESIGN_TEMPLATES.filter(
    (t) =>
      !t.mergedInto &&
      (!filter?.useCase || t.useCase === filter.useCase) &&
      (!filter?.kind || t.kind === filter.kind),
  );
}

/** The designs merged into one of vibld's examples, by the example's slug. */
export function designsForExample(slug: string): DesignTemplate[] {
  return DESIGN_TEMPLATES.filter((t) => t.mergedInto?.slug === slug);
}

/**
 * What a coding agent is given to build a template, as the catalog says to
 * use it: the baseline first, then the template's build prompt.
 */
export function designBrief(id: string): string | undefined {
  const template = findDesignTemplate(id);
  if (!template) return undefined;
  return `${DESIGN_BASELINE.trim()}\n\n## ${template.name}\n\n${template.buildPrompt.trim()}\n`;
}
