import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import {
  blobSha,
  branchForRevision,
  previewPush,
  pushCheckpoint,
  resolveBase,
} from '../worker/github-push.ts';

const FILES = [
  { path: 'index.html', content: '<h1>hi</h1>' },
  { path: 'src/main.ts', content: 'export const a = 1;' },
];

const REQUEST = {
  target: { owner: 'acme', repo: 'site', baseBranch: 'main' },
  files: FILES,
  // Resolved by `resolveBase` and held by the caller, so a retry commits
  // onto the same parent however the base branch has moved.
  baseSha: 'base-commit',
  revision: 'r7',
  message: 'vibld checkpoint r7',
  // Fixed, which is what makes the commit object deterministic.
  committer: {
    name: 'Vibld',
    email: 'noreply@vibld.com',
    date: '2026-09-13T12:00:00Z',
  },
  pullRequest: { title: 'vibld: r7', body: 'Generated by vibld.' },
};

interface Recorded {
  method: string;
  path: string;
  body: Record<string, unknown> | undefined;
}

/**
 * A GitHub that answers the five endpoints this client uses, from a
 * description of the repository's state rather than a script of replies, so a
 * test says what the repository is like instead of what order the calls come
 * in.
 */
function fakeGitHub(state: {
  /** Commit sha the base branch points at, or absent for an empty repo. */
  base?: string;
  /** Commit sha the vibld branch points at, if it is already there. */
  branch?: string;
  /** Tree sha that branch commit carries. */
  branchTree?: string;
  /** An already-open pull request for the branch. */
  openPull?: string;
  /** Force a failure on the call whose path contains this. */
  failOn?: {
    path: string;
    status: number;
    message?: string;
    headers?: Record<string, string>;
  };
  /**
   * The branch is absent when first read and present by the time the ref is
   * written: another retry winning the race. Its commit carries this tree.
   */
  appearsWithTree?: string;
  /** Branches the repository has, for telling empty apart from missing. */
  branches?: string[];
  /** What the base branch's commit holds, for the push preview. */
  baseTree?: {
    sha: string;
    entries: { path: string; type: string; sha: string }[];
    truncated?: boolean;
  };
}) {
  const calls: Recorded[] = [];
  let readTheBranch = false;
  const doFetch = (async (url: string, init?: RequestInit) => {
    const path = url.replace('https://api.github.com', '');
    const method = init?.method ?? 'GET';
    const body = init?.body
      ? (JSON.parse(init.body as string) as Record<string, unknown>)
      : undefined;
    calls.push({ method, path, body });

    const json = (value: unknown, status = 200) =>
      new Response(JSON.stringify(value), {
        status,
        headers: { 'content-type': 'application/json' },
      });

    if (state.failOn && path.includes(state.failOn.path)) {
      return new Response(
        JSON.stringify({ message: state.failOn.message ?? 'nope' }),
        {
          status: state.failOn.status,
          headers: {
            'content-type': 'application/json',
            ...(state.failOn.headers ?? {}),
          },
        },
      );
    }

    if (method === 'POST' && path.endsWith('/git/trees')) {
      return json({ sha: 'tree-of-these-files' }, 201);
    }
    if (method === 'GET' && path.endsWith('/git/ref/heads/main')) {
      return state.base
        ? json({ object: { sha: state.base } })
        : json({ message: 'Not Found' }, 404);
    }
    if (method === 'GET' && path.includes('/git/ref/heads/vibld/')) {
      if (state.appearsWithTree) {
        // Absent on the first read, there on the second.
        const wasRead = readTheBranch;
        readTheBranch = true;
        return wasRead
          ? json({ object: { sha: 'the-winner' } })
          : json({ message: 'Not Found' }, 404);
      }
      return state.branch
        ? json({ object: { sha: state.branch } })
        : json({ message: 'Not Found' }, 404);
    }
    if (method === 'GET' && path.includes('/git/matching-refs/heads/')) {
      return json(
        (state.branches ?? []).map((name) => ({ ref: `refs/heads/${name}` })),
      );
    }
    if (method === 'GET' && path.includes('/git/commits/')) {
      if (path.endsWith('/the-winner')) {
        return json({ tree: { sha: state.appearsWithTree } });
      }
      if (state.baseTree && state.base && path.endsWith(`/${state.base}`)) {
        return json({ tree: { sha: state.baseTree.sha } });
      }
      return json({ tree: { sha: state.branchTree ?? 'some-other-tree' } });
    }
    if (method === 'GET' && path.includes('/git/trees/')) {
      return json({
        tree: state.baseTree?.entries ?? [],
        truncated: state.baseTree?.truncated === true,
      });
    }
    if (method === 'POST' && path.endsWith('/git/commits')) {
      return json({ sha: 'new-commit' }, 201);
    }
    if (method === 'POST' && path.endsWith('/git/refs')) {
      return json({ ref: 'refs/heads/vibld/r7' }, 201);
    }
    if (method === 'GET' && path.includes('/pulls?')) {
      return json(state.openPull ? [{ html_url: state.openPull }] : []);
    }
    if (method === 'POST' && path.endsWith('/pulls')) {
      return json({ html_url: 'https://github.com/acme/site/pull/9' }, 201);
    }
    return json({ message: 'unexpected call' }, 500);
  }) as unknown as typeof fetch;

  return { doFetch, calls };
}

describe('naming the branch', () => {
  it('derives it from the revision, so a retry targets the same ref', () => {
    assert.equal(branchForRevision('r7'), 'vibld/r7');
    assert.equal(branchForRevision('r7'), branchForRevision('r7'));
  });

  it('refuses a revision that would not be a legal ref', () => {
    for (const revision of [
      'a/b',
      '../escape',
      '.hidden',
      'thing.lock',
      'with space',
      '',
      'x'.repeat(65),
    ]) {
      assert.equal(branchForRevision(revision), null, revision);
    }
  });
});

describe('pushing a checkpoint', () => {
  it('builds a tree, commits it, creates the ref and opens the pull request', async () => {
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);

    assert.equal(result.ok, true);
    if (!result.ok) return;
    assert.equal(result.pushed.branch, 'vibld/r7');
    assert.equal(result.pushed.commitSha, 'new-commit');
    assert.equal(result.pushed.created, true);
    assert.equal(
      result.pushed.pullRequestUrl,
      'https://github.com/acme/site/pull/9',
    );

    const commit = calls.find((c) => c.path.endsWith('/git/commits'));
    assert.deepEqual(commit?.body?.parents, ['base-commit']);
    assert.equal(commit?.body?.tree, 'tree-of-these-files');
  });

  it('sends the snapshot as the whole tree, so a dropped file is deleted', async () => {
    // `base_tree` omitted on purpose: the tree is exactly what was accepted,
    // which is the semantics the generation machine already has.
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    await pushCheckpoint('ghs_x', REQUEST, doFetch);
    const body = calls.find((c) => c.path.endsWith('/git/trees'))?.body ?? {};
    assert.equal(body.base_tree, undefined);
    assert.deepEqual(
      (body.tree as { path: string }[]).map((entry) => entry.path),
      ['index.html', 'src/main.ts'],
    );
  });

  it('commits with a fixed author and committer, so the sha is deterministic', async () => {
    // Git objects are content-addressed. With the date supplied, a commit
    // created by an attempt whose reply was lost is re-created identically
    // by the next one rather than becoming a second commit.
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    await pushCheckpoint('ghs_x', REQUEST, doFetch);
    const commit = calls.find((c) => c.path.endsWith('/git/commits'));
    assert.deepEqual(commit?.body?.author, REQUEST.committer);
    assert.deepEqual(commit?.body?.committer, REQUEST.committer);
  });

  it('never sends force, on any call', async () => {
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    await pushCheckpoint('ghs_x', REQUEST, doFetch);
    for (const recorded of calls) {
      assert.equal(
        'force' in (recorded.body ?? {}),
        false,
        `${recorded.method} ${recorded.path}`,
      );
    }
  });

  it('never writes the base branch', async () => {
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    await pushCheckpoint('ghs_x', REQUEST, doFetch);
    for (const recorded of calls) {
      if (recorded.method === 'GET') continue;
      const ref = String(recorded.body?.ref ?? '');
      assert.ok(!ref.includes('heads/main'), ref);
    }
  });
});

describe('a retry of a push whose reply was lost', () => {
  it('reports the commit already there rather than making a second one', async () => {
    // The branch exists and carries exactly this tree, so the earlier attempt
    // landed. Trees are content-addressed, which is what lets this be
    // answered by comparing rather than guessing.
    const { doFetch, calls } = fakeGitHub({
      base: 'base-commit',
      branch: 'already-committed',
      branchTree: 'tree-of-these-files',
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);

    assert.equal(result.ok, true);
    if (!result.ok) return;
    assert.equal(result.pushed.created, false);
    assert.equal(result.pushed.commitSha, 'already-committed');
    assert.equal(
      calls.some((c) => c.method === 'POST' && c.path.endsWith('/git/commits')),
      false,
      'committed a second time',
    );
    assert.equal(
      calls.some((c) => c.method === 'POST' && c.path.endsWith('/git/refs')),
      false,
      'wrote the ref a second time',
    );
  });

  it('does not open a second pull request either', async () => {
    const { doFetch, calls } = fakeGitHub({
      base: 'base-commit',
      branch: 'already-committed',
      branchTree: 'tree-of-these-files',
      openPull: 'https://github.com/acme/site/pull/4',
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, true);
    if (result.ok) {
      assert.equal(
        result.pushed.pullRequestUrl,
        'https://github.com/acme/site/pull/4',
      );
    }
    assert.equal(
      calls.some((c) => c.method === 'POST' && c.path.endsWith('/pulls')),
      false,
      'opened a duplicate pull request',
    );
  });
});

describe('a branch that is already something else', () => {
  it('reports the conflict with both shas and changes nothing', async () => {
    const { doFetch, calls } = fakeGitHub({
      base: 'base-commit',
      branch: 'someone-elses-commit',
      branchTree: 'a-different-tree',
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);

    assert.equal(result.ok, false);
    if (result.ok) return;
    assert.equal(result.conflict?.existingSha, 'someone-elses-commit');
    assert.equal(result.conflict?.attemptedTreeSha, 'tree-of-these-files');
    assert.match(result.error, /already exists/);
    assert.equal(
      calls.some((c) => c.method === 'POST' && c.path.endsWith('/git/refs')),
      false,
      'wrote a ref over a conflict',
    );
  });

  it('asks what won the race before calling it a conflict', async () => {
    // Two retries of the same push race each other. The winner wrote the
    // branch this attempt wanted, carrying the same tree, so the loser has
    // succeeded rather than collided. Reporting a conflict here would accuse
    // the user of something their own retry did.
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      appearsWithTree: 'tree-of-these-files',
      failOn: {
        path: '/git/refs',
        status: 422,
        message: 'Reference already exists',
      },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, true);
    if (result.ok) {
      assert.equal(result.pushed.created, false);
      assert.equal(result.pushed.commitSha, 'the-winner');
    }
  });

  it('still reports a conflict when something else won the race', async () => {
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      appearsWithTree: 'a-tree-from-elsewhere',
      failOn: {
        path: '/git/refs',
        status: 422,
        message: 'Reference already exists',
      },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) assert.equal(result.conflict?.existingSha, 'the-winner');
  });
});

describe('when GitHub says no', () => {
  it('reports lost access in words rather than a status code', async () => {
    for (const status of [401, 403]) {
      const { doFetch } = fakeGitHub({
        base: 'base-commit',
        failOn: { path: '/git/trees', status },
      });
      const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
      assert.equal(result.ok, false);
      if (!result.ok) assert.match(result.error, /no longer has access/);
    }
  });

  it("passes GitHub's own explanation through for the ones it explains", async () => {
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: { path: '/git/trees', status: 422, message: 'path is invalid' },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) assert.match(result.error, /path is invalid/);
  });

  it('still reports the push when only the pull request fails', async () => {
    // A branch that pushed and a pull request that did not open is a success
    // with a missing link, not a failed push.
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: { path: '/pulls', status: 500 },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, true);
    if (result.ok) assert.equal(result.pushed.pullRequestUrl, undefined);
  });

  it('refuses an empty snapshot instead of committing nothing', async () => {
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    const result = await pushCheckpoint(
      'ghs_x',
      { ...REQUEST, files: [] },
      doFetch,
    );
    assert.equal(result.ok, false);
    assert.equal(calls.length, 0);
  });
});

describe('resolving the base commit', () => {
  it('returns the commit the base branch points at', async () => {
    const { doFetch } = fakeGitHub({ base: 'base-commit' });
    const result = await resolveBase('ghs_x', REQUEST.target, doFetch);
    assert.equal(result.ok, true);
    if (result.ok) assert.equal(result.sha, 'base-commit');
  });

  it('says the branch is gone when the repository has history', async () => {
    // A renamed or deleted base branch answers 404 exactly like an empty
    // repository does, and building a parentless commit for it would make a
    // branch related to nothing.
    const { doFetch } = fakeGitHub({ branches: ['trunk', 'dev'] });
    const result = await resolveBase('ghs_x', REQUEST.target, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) assert.match(result.error, /main no longer exists/);
  });

  it('says the repository is empty when it has no branches at all', async () => {
    // Refused rather than half-supported: creating the first commit of an
    // empty repository through this API is a different flow, and claiming a
    // path that has never run is worse than saying what to do instead.
    const { doFetch } = fakeGitHub({ branches: [] });
    const result = await resolveBase('ghs_x', REQUEST.target, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) assert.match(result.error, /no commits yet/);
  });

  it('is a separate step so the caller can record it first', async () => {
    // The parent has to exist on the caller's side before anything
    // ambiguous happens. A push that resolved its own parent and then lost
    // the reply to the commit call left nothing to pin, and the retry read
    // a branch that may have moved.
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(
      calls.some((c) => c.path.endsWith('/git/ref/heads/main')),
      false,
      'the push read the base branch itself',
    );
  });
});

describe('a lookup that fails rather than disagrees', () => {
  it('does not call an unreadable commit a conflict', async () => {
    // The branch is there and carries the right tree, but the commit lookup
    // fails. Collapsing that into "points somewhere else" accuses the user
    // of having moved a branch nobody managed to read.
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      branch: 'already-committed',
      branchTree: 'tree-of-these-files',
      failOn: { path: '/git/commits/already-committed', status: 500 },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) {
      assert.equal(result.conflict, undefined);
      assert.doesNotMatch(result.error, /already exists/);
    }
  });
});

describe('a 403 that is not revoked access', () => {
  it('reads a rate limit as a rate limit', async () => {
    // GitHub uses 403 for both, and only the headers tell them apart.
    // Sending someone to reconnect an App that is working perfectly well is
    // the wrong one of the two.
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: {
        path: '/git/trees',
        status: 403,
        headers: { 'x-ratelimit-remaining': '0' },
      },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) {
      assert.match(result.error, /rate limiting/);
      assert.doesNotMatch(result.error, /no longer has access/);
    }
  });

  it('passes on how long to wait when GitHub says', async () => {
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: {
        path: '/git/trees',
        status: 403,
        headers: { 'retry-after': '60' },
      },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) assert.match(result.error, /60 seconds/);
  });

  it('reads a 429 as a rate limit without needing headers', async () => {
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: {
        path: '/git/trees',
        status: 429,
        headers: { 'retry-after': '30' },
      },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) assert.match(result.error, /30 seconds/);
  });

  it('reads a secondary limit that arrives with no useful headers', async () => {
    // GitHub documents that either header may be absent on a secondary
    // limit, and says so in the body instead. A predicate gated on the two
    // headers calls that revoked access.
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: {
        path: '/git/trees',
        status: 403,
        message:
          'You have exceeded a secondary rate limit and have been temporarily blocked from content creation.',
      },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) {
      assert.match(result.error, /rate limiting/);
      assert.doesNotMatch(result.error, /no longer has access/);
    }
  });

  it('still reads a plain 403 as revoked access', async () => {
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: { path: '/git/trees', status: 403 },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) assert.match(result.error, /no longer has access/);
  });
});

describe('refs with characters that mean something in a URL', () => {
  it('encodes the base branch instead of losing half of it', async () => {
    // `release#1` is a legal git ref. Interpolated raw, `#1` becomes the URL
    // fragment and the request asks for `heads/release`: either the branch
    // is reported missing, or a shorter branch by that name silently
    // supplies the wrong parent.
    const asked: string[] = [];
    const doFetch = (async (url: string) => {
      asked.push(url);
      return new Response(JSON.stringify({ object: { sha: 'x' } }), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
    }) as unknown as typeof fetch;

    await resolveBase(
      'ghs_x',
      { owner: 'acme', repo: 'site', baseBranch: 'release#1' },
      doFetch,
    );
    assert.ok(
      asked[0]?.endsWith('/git/ref/heads/release%231'),
      `asked for ${asked[0]}`,
    );
  });

  it('leaves the separators alone while encoding the parts', async () => {
    const asked: string[] = [];
    const doFetch = (async (url: string) => {
      asked.push(url);
      return new Response(JSON.stringify({ object: { sha: 'x' } }), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
    }) as unknown as typeof fetch;

    await resolveBase(
      'ghs_x',
      { owner: 'acme', repo: 'site', baseBranch: 'release/2026' },
      doFetch,
    );
    assert.ok(
      asked[0]?.endsWith('/git/ref/heads/release/2026'),
      `asked for ${asked[0]}`,
    );
  });
});

describe('naming a blob the way git does', () => {
  it('matches git for content git has a published sha for', async () => {
    // Pinned against git itself rather than against this implementation.
    // These two shas are what `git hash-object` produces, so a change to the
    // header, the encoding or the algorithm fails here rather than quietly
    // reporting every file as changed.
    assert.equal(await blobSha(''), 'e69de29bb2d1d6434b8b29ae775ad8c2e48c5391');
    assert.equal(
      await blobSha('hello\n'),
      'ce013625030ba8dba906f756967f9e9ca394464a',
    );
  });

  it('counts the length in bytes, not characters', async () => {
    // The bug waiting in any implementation that reaches for `.length`, and
    // it only shows against content where the two differ. These shas were
    // computed independently of this code, from git's own definition: sha1
    // of "blob <bytes>", a NUL, and the UTF-8 bytes. One accent makes the
    // header wrong, git has never heard of the result, and every such file
    // reads as changed on every preview.
    //
    // Comparing two of our own hashes cannot catch this: under a
    // character-counting header they still differ from each other. Only a
    // value git itself would produce pins it.
    assert.equal(
      await blobSha('\u00e9'),
      '4b04fff51468d8ab5201ab02b725dc477bc7cb45',
    );
    assert.equal(
      await blobSha('h\u00e9llo w\u00f6rld\n'),
      '9d4a8bab579c9317dc648e018736aec79914b21a',
    );
    // One character, four bytes, in case two ever looks like a coincidence.
    assert.equal(
      await blobSha('\ud83c\udf0d'),
      '332fdb853175d1ecfa60cdacb5f83e9f2ce33a88',
    );
  });
});

describe('previewing what a push would do', () => {
  const target = { owner: 'acme', repo: 'site', baseBranch: 'main' };

  async function treeOf(files: { path: string; content: string }[]) {
    return Promise.all(
      files.map(async (file) => ({
        path: file.path,
        type: 'blob',
        sha: await blobSha(file.content),
      })),
    );
  }

  it('separates what it adds, changes, removes and leaves alone', async () => {
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      baseTree: {
        sha: 'base-tree',
        entries: [
          ...(await treeOf([
            { path: 'index.html', content: '<h1>old</h1>' },
            { path: 'src/main.ts', content: 'export const a = 1;' },
            { path: 'README.md', content: 'kept by nobody' },
          ])),
        ],
      },
    });

    const result = await previewPush('tok', target, FILES, doFetch);

    assert.ok(result.ok);
    // `src/main.ts` is byte-identical in FILES, `index.html` is not, and
    // README.md is in the repository and not in the snapshot.
    assert.deepEqual(result.preview.changed, ['index.html']);
    assert.equal(result.preview.unchanged, 1);
    assert.deepEqual(result.preview.removed, ['README.md']);
    assert.deepEqual(result.preview.added, []);
  });

  it('names every deletion the push would make', async () => {
    // The half that most needs showing: the tree is built without
    // `base_tree`, so a file the repository has and the snapshot does not is
    // gone from the branch. A button marked "push" does not say that.
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      baseTree: {
        sha: 'base-tree',
        entries: await treeOf([
          { path: 'index.html', content: '<h1>hi</h1>' },
          { path: 'src/main.ts', content: 'export const a = 1;' },
          { path: 'LICENSE', content: 'MIT' },
          { path: 'docs/guide.md', content: '# guide' },
        ]),
      },
    });

    const result = await previewPush('tok', target, FILES, doFetch);

    assert.ok(result.ok);
    assert.deepEqual(result.preview.removed, ['LICENSE', 'docs/guide.md']);
    assert.equal(result.preview.unchanged, 2);
  });

  it('counts an empty repository as all additions and no deletions', async () => {
    // Unlike `resolveBase`, a missing base branch is an answerable question
    // here: everything is new and nothing is lost.
    const { doFetch } = fakeGitHub({});

    const result = await previewPush('tok', target, FILES, doFetch);

    assert.ok(result.ok);
    assert.deepEqual(result.preview.added, ['index.html', 'src/main.ts']);
    assert.deepEqual(result.preview.removed, []);
    assert.equal(result.preview.baseSha, null);
  });

  it('says when the listing was truncated rather than under-reporting', async () => {
    // A short deletion list is the one number nobody should read
    // optimistically. If GitHub would not list the whole tree, the preview
    // says so instead of implying the push removes less than it does.
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      baseTree: {
        sha: 'base-tree',
        entries: await treeOf([{ path: 'LICENSE', content: 'MIT' }]),
        truncated: true,
      },
    });

    const result = await previewPush('tok', target, FILES, doFetch);

    assert.ok(result.ok);
    assert.equal(result.preview.truncated, true);
  });

  it('ignores a submodule rather than calling it a deletion', async () => {
    // A `commit` entry is a submodule. A push neither writes nor removes
    // one, so announcing it as removed would promise something this cannot
    // do.
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      baseTree: {
        sha: 'base-tree',
        entries: [
          ...(await treeOf([{ path: 'index.html', content: '<h1>hi</h1>' }])),
          { path: 'vendor/lib', type: 'commit', sha: 'submodule-sha' },
        ],
      },
    });

    const result = await previewPush('tok', target, FILES, doFetch);

    assert.ok(result.ok);
    assert.deepEqual(result.preview.removed, []);
  });

  it('writes nothing while answering', async () => {
    const { doFetch, calls } = fakeGitHub({
      base: 'base-commit',
      baseTree: { sha: 'base-tree', entries: [] },
    });

    await previewPush('tok', target, FILES, doFetch);

    assert.deepEqual(
      calls.filter((call) => call.method !== 'GET'),
      [],
      'the preview made a request that was not a read',
    );
  });

  it('reports a lost repository as access, not as an empty diff', async () => {
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: { path: '/git/ref/heads/main', status: 403 },
    });

    const result = await previewPush('tok', target, FILES, doFetch);

    assert.equal(result.ok, false);
    assert.equal(result.ok === false && result.reason, 'access');
  });
});
