import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { branchForRevision, pushCheckpoint } from '../worker/github-push.ts';

const FILES = [
  { path: 'index.html', content: '<h1>hi</h1>' },
  { path: 'src/main.ts', content: 'export const a = 1;' },
];

const REQUEST = {
  target: { owner: 'acme', repo: 'site', baseBranch: 'main' },
  files: FILES,
  revision: 'r7',
  message: 'Vibld checkpoint r7',
  pullRequest: { title: 'Vibld: r7', body: 'Generated by Vibld.' },
};

interface Recorded {
  method: string;
  path: string;
  body: Record<string, unknown> | undefined;
}

/**
 * A GitHub that answers the five endpoints this client uses, from a
 * description of the repository's state rather than a script of replies, so a
 * test says what the repository is like instead of what order the calls come
 * in.
 */
function fakeGitHub(state: {
  /** Commit sha the base branch points at, or absent for an empty repo. */
  base?: string;
  /** Commit sha the vibld branch points at, if it is already there. */
  branch?: string;
  /** Tree sha that branch commit carries. */
  branchTree?: string;
  /** An already-open pull request for the branch. */
  openPull?: string;
  /** Force a failure on the call whose path contains this. */
  failOn?: { path: string; status: number; message?: string };
}) {
  const calls: Recorded[] = [];
  const doFetch = (async (url: string, init?: RequestInit) => {
    const path = url.replace('https://api.github.com', '');
    const method = init?.method ?? 'GET';
    const body = init?.body
      ? (JSON.parse(init.body as string) as Record<string, unknown>)
      : undefined;
    calls.push({ method, path, body });

    const json = (value: unknown, status = 200) =>
      new Response(JSON.stringify(value), {
        status,
        headers: { 'content-type': 'application/json' },
      });

    if (state.failOn && path.includes(state.failOn.path)) {
      return json(
        { message: state.failOn.message ?? 'nope' },
        state.failOn.status,
      );
    }

    if (method === 'POST' && path.endsWith('/git/trees')) {
      return json({ sha: 'tree-of-these-files' }, 201);
    }
    if (method === 'GET' && path.endsWith('/git/ref/heads/main')) {
      return state.base
        ? json({ object: { sha: state.base } })
        : json({ message: 'Not Found' }, 404);
    }
    if (method === 'GET' && path.includes('/git/ref/heads/vibld/')) {
      return state.branch
        ? json({ object: { sha: state.branch } })
        : json({ message: 'Not Found' }, 404);
    }
    if (method === 'GET' && path.includes('/git/commits/')) {
      return json({ tree: { sha: state.branchTree ?? 'some-other-tree' } });
    }
    if (method === 'POST' && path.endsWith('/git/commits')) {
      return json({ sha: 'new-commit' }, 201);
    }
    if (method === 'POST' && path.endsWith('/git/refs')) {
      return json({ ref: 'refs/heads/vibld/r7' }, 201);
    }
    if (method === 'GET' && path.includes('/pulls?')) {
      return json(state.openPull ? [{ html_url: state.openPull }] : []);
    }
    if (method === 'POST' && path.endsWith('/pulls')) {
      return json({ html_url: 'https://github.com/acme/site/pull/9' }, 201);
    }
    return json({ message: 'unexpected call' }, 500);
  }) as unknown as typeof fetch;

  return { doFetch, calls };
}

describe('naming the branch', () => {
  it('derives it from the revision, so a retry targets the same ref', () => {
    assert.equal(branchForRevision('r7'), 'vibld/r7');
    assert.equal(branchForRevision('r7'), branchForRevision('r7'));
  });

  it('refuses a revision that would not be a legal ref', () => {
    for (const revision of [
      'a/b',
      '../escape',
      '.hidden',
      'thing.lock',
      'with space',
      '',
      'x'.repeat(65),
    ]) {
      assert.equal(branchForRevision(revision), null, revision);
    }
  });
});

describe('pushing a checkpoint', () => {
  it('builds a tree, commits it, creates the ref and opens the pull request', async () => {
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);

    assert.equal(result.ok, true);
    if (!result.ok) return;
    assert.equal(result.pushed.branch, 'vibld/r7');
    assert.equal(result.pushed.commitSha, 'new-commit');
    assert.equal(result.pushed.created, true);
    assert.equal(
      result.pushed.pullRequestUrl,
      'https://github.com/acme/site/pull/9',
    );

    const commit = calls.find((c) => c.path.endsWith('/git/commits'));
    assert.deepEqual(commit?.body?.parents, ['base-commit']);
    assert.equal(commit?.body?.tree, 'tree-of-these-files');
  });

  it('sends the snapshot as the whole tree, so a dropped file is deleted', async () => {
    // `base_tree` omitted on purpose: the tree is exactly what was accepted,
    // which is the semantics the generation machine already has.
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    await pushCheckpoint('ghs_x', REQUEST, doFetch);
    const body = calls.find((c) => c.path.endsWith('/git/trees'))?.body ?? {};
    assert.equal(body.base_tree, undefined);
    assert.deepEqual(
      (body.tree as { path: string }[]).map((entry) => entry.path),
      ['index.html', 'src/main.ts'],
    );
  });

  it('commits without a parent into an empty repository', async () => {
    const { doFetch, calls } = fakeGitHub({});
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, true);
    const commit = calls.find((c) => c.path.endsWith('/git/commits'));
    // Absent, not empty: GitHub wants the field left off entirely.
    assert.equal('parents' in (commit?.body ?? {}), false);
  });

  it('never sends force, on any call', async () => {
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    await pushCheckpoint('ghs_x', REQUEST, doFetch);
    for (const recorded of calls) {
      assert.equal(
        'force' in (recorded.body ?? {}),
        false,
        `${recorded.method} ${recorded.path}`,
      );
    }
  });

  it('never writes the base branch', async () => {
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    await pushCheckpoint('ghs_x', REQUEST, doFetch);
    for (const recorded of calls) {
      if (recorded.method === 'GET') continue;
      const ref = String(recorded.body?.ref ?? '');
      assert.ok(!ref.includes('heads/main'), ref);
    }
  });
});

describe('a retry of a push whose reply was lost', () => {
  it('reports the commit already there rather than making a second one', async () => {
    // The branch exists and carries exactly this tree, so the earlier attempt
    // landed. Trees are content-addressed, which is what lets this be
    // answered by comparing rather than guessing.
    const { doFetch, calls } = fakeGitHub({
      base: 'base-commit',
      branch: 'already-committed',
      branchTree: 'tree-of-these-files',
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);

    assert.equal(result.ok, true);
    if (!result.ok) return;
    assert.equal(result.pushed.created, false);
    assert.equal(result.pushed.commitSha, 'already-committed');
    assert.equal(
      calls.some((c) => c.method === 'POST' && c.path.endsWith('/git/commits')),
      false,
      'committed a second time',
    );
    assert.equal(
      calls.some((c) => c.method === 'POST' && c.path.endsWith('/git/refs')),
      false,
      'wrote the ref a second time',
    );
  });

  it('does not open a second pull request either', async () => {
    const { doFetch, calls } = fakeGitHub({
      base: 'base-commit',
      branch: 'already-committed',
      branchTree: 'tree-of-these-files',
      openPull: 'https://github.com/acme/site/pull/4',
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, true);
    if (result.ok) {
      assert.equal(
        result.pushed.pullRequestUrl,
        'https://github.com/acme/site/pull/4',
      );
    }
    assert.equal(
      calls.some((c) => c.method === 'POST' && c.path.endsWith('/pulls')),
      false,
      'opened a duplicate pull request',
    );
  });
});

describe('a branch that is already something else', () => {
  it('reports the conflict with both shas and changes nothing', async () => {
    const { doFetch, calls } = fakeGitHub({
      base: 'base-commit',
      branch: 'someone-elses-commit',
      branchTree: 'a-different-tree',
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);

    assert.equal(result.ok, false);
    if (result.ok) return;
    assert.equal(result.conflict?.existingSha, 'someone-elses-commit');
    assert.equal(result.conflict?.attemptedTreeSha, 'tree-of-these-files');
    assert.match(result.error, /already exists/);
    assert.equal(
      calls.some((c) => c.method === 'POST' && c.path.endsWith('/git/refs')),
      false,
      'wrote a ref over a conflict',
    );
  });

  it('treats losing the race on ref creation as a conflict, not an overwrite', async () => {
    // The ref appeared between the read and the write. That is another
    // attempt winning, not a reason to force.
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: {
        path: '/git/refs',
        status: 422,
        message: 'Reference already exists',
      },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) assert.ok(result.conflict);
  });
});

describe('when GitHub says no', () => {
  it('reports lost access in words rather than a status code', async () => {
    for (const status of [401, 403]) {
      const { doFetch } = fakeGitHub({
        base: 'base-commit',
        failOn: { path: '/git/trees', status },
      });
      const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
      assert.equal(result.ok, false);
      if (!result.ok) assert.match(result.error, /no longer has access/);
    }
  });

  it("passes GitHub's own explanation through for the ones it explains", async () => {
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: { path: '/git/trees', status: 422, message: 'path is invalid' },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, false);
    if (!result.ok) assert.match(result.error, /path is invalid/);
  });

  it('still reports the push when only the pull request fails', async () => {
    // A branch that pushed and a pull request that did not open is a success
    // with a missing link, not a failed push.
    const { doFetch } = fakeGitHub({
      base: 'base-commit',
      failOn: { path: '/pulls', status: 500 },
    });
    const result = await pushCheckpoint('ghs_x', REQUEST, doFetch);
    assert.equal(result.ok, true);
    if (result.ok) assert.equal(result.pushed.pullRequestUrl, undefined);
  });

  it('refuses an empty snapshot instead of committing nothing', async () => {
    const { doFetch, calls } = fakeGitHub({ base: 'base-commit' });
    const result = await pushCheckpoint(
      'ghs_x',
      { ...REQUEST, files: [] },
      doFetch,
    );
    assert.equal(result.ok, false);
    assert.equal(calls.length, 0);
  });
});
