import { LegalPage } from '../components/SiteChrome';
import { LEGAL_DOCS, SITE, metaFor } from '../site';

const DOC = LEGAL_DOCS.find((d) => d.slug === 'privacy')!;
const UPDATED = '2026-09-10';

export function meta() {
  return metaFor('/legal/privacy');
}

export default function Privacy() {
  return (
    <LegalPage title={DOC.label} updated={UPDATED}>
      <p>
        This policy describes what {SITE.legalEntity} (&ldquo;{SITE.name}
        &rdquo;, &ldquo;we&rdquo;) collects through this website today, while
        Vibld is in its pre-launch waitlist phase. It will be expanded before
        the product itself launches, since account, project, and billing data do
        not exist yet.
      </p>

      <h2>What we collect</h2>
      <p>Right now, this site collects:</p>
      <ul>
        <li>
          <strong>The email address you submit</strong> to join the waitlist.
        </li>
        <li>
          <strong>Standard server and network logs</strong> generated by our
          hosting provider, Cloudflare, Inc. (IP address, user agent, request
          timing). We do not attach these to your identity beyond what
          Cloudflare retains operationally, and we do not run any analytics or
          advertising scripts on this site. See our{' '}
          <a href="/legal/cookies">Cookie Notice</a>.
        </li>
      </ul>

      <h2>Why we collect it</h2>
      <p>
        We use your email address to notify you when Vibld becomes available and
        to send occasional updates about the product before then. We do not use
        it for any other purpose, and we do not sell it.
      </p>

      <h2>Who we share it with</h2>
      <p>
        Your email address is stored with Resend, our email-delivery processor,
        so that we can send you the notifications above. See our{' '}
        <a href="/legal/subprocessors">Subprocessors</a> page for the current
        list of services that process data on our behalf. We do not sell
        personal information, and we do not share it with anyone for their own
        marketing purposes.
      </p>

      <h2>How long we keep it</h2>
      <p>
        We keep your email address until you unsubscribe, ask us to delete it,
        or Vibld launches and the waitlist is retired — whichever comes first.
      </p>

      <h2>Your choices</h2>
      <p>
        Every email we send includes an unsubscribe link. You can also request
        access to, correction of, or deletion of your information at any time by
        emailing{' '}
        <a href={`mailto:${SITE.emails.privacy}`}>{SITE.emails.privacy}</a>. We
        will respond within a reasonable time.
      </p>

      <h2>Children</h2>
      <p>
        This site is not directed at children under 13, and we do not knowingly
        collect information from them.
      </p>

      <h2>Where this applies</h2>
      <p>
        The Service is offered to, and this site is intended for, users located
        in the United States. We do not currently offer the Service to residents
        of the European Union, the United Kingdom, or other jurisdictions with
        their own data-transfer requirements. See our{' '}
        <a href="/legal/terms">Terms of Service</a>.
      </p>

      <h2>Changes to this policy</h2>
      <p>
        As Vibld moves from a waitlist to a live product, this policy will be
        replaced with a version covering accounts, projects, and payment data.
        We will update the &ldquo;Last updated&rdquo; date whenever we do, and
        for material changes we will notify waitlist members by email.
      </p>

      <h2>Contact</h2>
      <p>
        Questions or requests about this policy can be sent to{' '}
        <a href={`mailto:${SITE.emails.privacy}`}>{SITE.emails.privacy}</a> or
        to {SITE.legalEntity}, {SITE.mailingAddress}.
      </p>
    </LegalPage>
  );
}
